### ISSUE TITLE
Make Logs tab work as a partial

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#1001]
Similar with the Details widget https://github.com/evercam/evercam-dashboard/issues/999

The logs page needs to be more responsive on small screens. This is how it currently looks like:

<img width="381" alt="screen shot 2016-03-14 at 17 07 22" src="https://cloud.githubusercontent.com/assets/5046761/13752708/efd2a49c-ea07-11e5-9254-dfe5cc70e0b7.png">

**Comment by marcoherbst** [comment]
Remember:
1. Dont do this as a widget. Remember Milos' advice about using a partial.
2. Your primary task here is to get it working responsively.

**Comment by muneeb2542** [comment]
@mosic Could you advise me on how to proceed on this using logs partial as a separate page for an alternative to widget?

**Comment by mosic** [comment]
@muneeb2542 You can take a look at how the swagger page was implemented as an example, that might help: https://github.com/evercam/evercam-dashboard/blob/master/app/views/layouts/swagger.html.erb

**Comment by marcoherbst** [comment]
@muneeb2542  let's split this into 2 tasks:

1. responsive (urgent)
2. as a partial (not urgent)

Will you make the issues please.

**Comment by marcoherbst** [comment]
I'll take this task out of here and put it on the long finger. It's no longer important.

**Comment by affan00** [comment]
Logs tab is already worked as a partial, So, I am closing this now.
