### ISSUE TITLE
Snapshot navigator widget is looking weird on iPAD

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#1006]
The view is blinking a lot.
![screenshot from 2016-03-16 10-35-18](https://cloud.githubusercontent.com/assets/6482077/13802968/d6598e0c-eb62-11e5-9572-0520c9bae8fd.png)

**Comment by muneeb2542** [comment]
@liutingdu Affan has fixed some layout issues in the widget, So do the problem still persist on iPAD?

**Comment by liutingdu** [comment]
@muneeb2542 Tested it again but the issue still exists. It should be related to the button to show/hide calendar. When calendar is hidden, the problem disappeared. Let me know if you need any further details.

**Comment by marcoherbst** [comment]
Does this help: http://www.htmlgoodies.com/beyond/webmaster/toolbox/article.php/3889011/Using-Safari-for-iPhone-iPad-and-iPod-Touch-Website-Testing.htm
? @muneeb2542

**Comment by marcoherbst** [comment]
And, I think we now have an OSX device in the office @Zulqarnain-Mustafa  :) .... he might help you out !

**Comment by muneeb2542** [comment]
yes, I will ask him.

**Comment by liutingdu** [comment]
@Zulqarnain-Mustafa can certainly help reproduce it on an iPad 2 simulator. He knows more about iOS and it would help further diagnose the issue.

**Comment by muneeb2542** [comment]
@liutingdu sorry to ask you this  but is this error happening on an iPad browser or on the ios app?

**Comment by marcoherbst** [comment]
iPad browser - you should be able to recreate it on safari at the right resolution. Google will be your friend here, there are developer tools for this to simulate it. See the link I posted above, for example. I think.

**Comment by liutingdu** [comment]
@muneeb2542 

I reproduced it the iOS app, we use a WebView in the iOS app for cloud recording. 

I tried it in Safari on iPad and on my laptop but wasn't able  to reproduce it.

There are [differences between iOS webview and Safari](http://stackoverflow.com/questions/11648184/uiwebview-and-safari-comparison) and that's why I suggested that @Zulqarnain-Mustafa might help (In Android, there is [a Chrome plugin](https://developer.chrome.com/devtools/docs/remote-debugging) for debugging WebView on Android phone in laptop Chrome)

**Comment by muneeb2542** [comment]
yes that is why i asked because i have been trying to reproduce this error on multiple simulators and was not successfull.
i will now coordinate with @Zulqarnain-Mustafa  on this.

**Comment by muneeb2542** [comment]
@liutingdu can you tell me what is your ios version and which version of iPad are you using?

**Comment by liutingdu** [comment]
The real device is: iPad Air iOS 9.3.1
Xcode Simulator: iPad 2

**Comment by muneeb2542** [comment]
@liutingdu I have tested on both these iPad versions using Xcode simulator and still was not able to replicate the issue.

**Comment by liutingdu** [comment]
Follow the steps:
1. Open the app, in portrait, choose a camera and go to the cloud recording page
2. Rotate the device then you will see it

**Comment by muneeb2542** [comment]
yes now i see it.Will look into it.

**Comment by muneeb2542** [comment]
Done
