### ISSUE TITLE
[Airbrake] [Production] PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1010]
**Airbrake error:** [#0339](https://evercam.airbrake.io/projects/98599/groups/1642753606670250339)
**Airbrake project:** Evercam Dashboard

**Error type:** `Sequel::DatabaseConnectionError`
**Error message:** `PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections`
**Occurred at:** Mar 16, 2016 13:38:10 UTC
**First seen at:** Mar 16, 2016 13:38:10 UTC
**Occurrences:** 1 (0 since last deploy on Time not available)

**URL:** [https://dash.evercam.io/v1/cameras/bolands-mills-markerptz](https://dash.evercam.io/v1/cameras/bolands-mills-markerptz)
**File:** `[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/postgres.rb`

**Backtrace:**
```
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/postgres.rb:237:in initialize
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/postgres.rb:237:in new
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/sequel-4.26.0/lib/sequel/adapters/postgres.rb:237:in connect
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/sequel-4.26.0/lib/sequel/connection_pool.rb:101:in make_new
```

**Comment by marcoherbst** [comment]
@muneeb2542 since these are all for you ... can you set airbrake to assign you automatically?

**Comment by muneeb2542** [comment]
This issue is not relevant.

Closing this.
