### ISSUE TITLE
[Airbrake] [Production] undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1026]
**Airbrake error:** [#0720](https://evercam.airbrake.io/projects/98599/groups/1647056875919930720)
**Airbrake project:** Evercam Dashboard

**Error type:** `NoMethodError`
**Error message:** `undefined method `each' for nil:NilClass`
**Occurred at:** Mar 22, 2016 12:07:59 UTC
**First seen at:** Mar 22, 2016 12:07:59 UTC
**Occurrences:** 1 (0 since last deploy on Time not available)

**URL:** [https://dash.evercam.io/v1/users/azharmalik3/billing](https://dash.evercam.io/v1/users/azharmalik3/billing)
**File:** `[PROJECT_ROOT]/app/views/shared/_sidebar.html.erb`

**Backtrace:**
```
[PROJECT_ROOT]/app/views/shared/_sidebar.html.erb:25:in _app_views_shared__sidebar_html_erb__322604727180868296_70134512095800
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.1/lib/action_view/template.rb:145:in block in render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in instrument
```

**Comment by muneeb2542** [comment]
This issue is solved now.It only happened because while deployment of a new branch something was missing and after we added them,the error stopped showing.
