### ISSUE TITLE
In the case of a redirect for a not logged in user, give a more friendly screen

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1054]
Currently we just bring the person to the login screen.

Instead we want to bring them to a screen that explains why they are there

"To view this camera, you need to either login or to create an Evercam account."

and offers them a clear choice between signing up or logging in.

@affan00 this is a chance to do a nice mockup.

**Comment by marcoherbst** [comment]
It's for another day, but many websites combine the Sign Up / Log in pages more smoothly. And, NB, we will be adding SSO options.....

Affan, for now though, I'd just try to consider the reasons someone got to this page and what message we want to show them (the original task).

**Comment by affan00** [comment]
Yes, I got your point and will do it and show you the result first on
localtunnel.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by marcoherbst** [comment]
1. Non logged in user tries to visit a private camera, e.g. https://dash.evercam.io/v1/cameras/ccccccc/
2. They are re-directed to login page with a message "This is a private camera..."
3. They login or signup & are re-directed to the camera.

**Comment by affan00** [comment]
It's done,
If not logged in user tried to visit the single-camera page it will redirect to the sign in page with notification "This is a private camera, To view this camera either Sign in below or Create New Account" and after sign in user will redirect back to the requested URL.
