### ISSUE TITLE
In embed live view we should give user the option of 'px' and '%' and by default image size should be 100% instead of '400px' so that image is responsive for every media screen.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1058]
and now when we write the value in % it gives error "to write in px" but shows the result, fix this.

![errors](https://cloud.githubusercontent.com/assets/14149453/14135446/dd257eac-f676-11e5-8c0c-a5a95486208c.png)

![live-view-image-cut](https://cloud.githubusercontent.com/assets/14149453/14135389/9bcbfd5a-f676-11e5-9eb3-6f6ce2134156.png)

**Comment by marcoherbst** [comment]
Nice one @affan00 . Lovely.

**Comment by affan00** [comment]
done
