### ISSUE TITLE
The responsive menus dont align very well on the dashboard when in mobile view

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1065]
![screenshot 2016-03-30 17 42 24](https://cloud.githubusercontent.com/assets/5648894/14150024/f683241c-f69e-11e5-972a-61a1b329accf.png)

See here how the 2 menus aren't aligned properly. To my eye, the lower one needs to align to the right and whichever icon is being used should be consistent with both of them.

By the way, in general, the performance of the dashboard on mobile is really excellent -  rivalling the native app experience and worthy of attention from @liutingdu and @Zulqarnain-Mustafa

**Comment by liutingdu** [comment]
Should we move the top menu icon to the left of the title bar?

**Comment by affan00** [comment]
its fixed and live now.
