### ISSUE TITLE
Increasing vertical space during landscape desktop view (and minor changes)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1069]
- [x] Move three bars on responsive site to the left side.

- [x] For normal landscape, desktop view, get rid of title bar. (move everything up)

- [x] On mobile, portrait mode  - keep the title bar.

- [x] Get rid of “open in new window” icon on left bar.

- [x] Live chat icon - http://fortawesome.github.io/Font-Awesome/icon/comment/ (mobile also @liutingdu )

**Comment by affan00** [comment]
it's done
