### ISSUE TITLE
[Airbrake] [Production] Network is unreachable - connect(2) for "freegeoip.net" port 80

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1070]
**Airbrake error:** [#2410](https://evercam.airbrake.io/projects/98599/groups/1653965372012002410)
**Airbrake project:** Evercam Dashboard

**Error type:** `Errno::ENETUNREACH`
**Error message:** `Network is unreachable - connect(2) for "freegeoip.net" port 80`
**Where:** `users#new`
**Occurred at:** Apr 01, 2016 00:53:56 UTC
**First seen at:** Apr 01, 2016 00:53:56 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://auth.evercam.io/v1/users/signup](https://auth.evercam.io/v1/users/signup)
**File:** `[PROJECT_ROOT]/vendor/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb`

**Backtrace:**
```
[PROJECT_ROOT]/vendor/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in initialize
[PROJECT_ROOT]/vendor/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in open
[PROJECT_ROOT]/vendor/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in block in connect
[PROJECT_ROOT]/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in block in timeout
```

**Comment by muneeb2542** [comment]
This is irrelevant now.

Closing it
