### ISSUE TITLE
Change the layout of the schedule calendar window

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1076]
https://cloud.githubusercontent.com/assets/5648894/13608884/974282e2-e54e-11e5-9dcf-50afabf7ac20.png

- [x] Recording settings should be shown on popup window.
- [x] On click calendar icon the whole right column should be hide and snapshot section should expand.
- [x] Show scheduled text below the recording setting button.

**Comment by marcoherbst** [comment]
I'm taking this out of long finger and bringing it up ... as I just tried to use the current schedule and it's really terrible ... really terrible. This needs work as a priority. How do you choose 2pm - 7pm? 

And, please change the labels:
On
On (Scheduled)
Off

Should be:
Always On
Scheduled
Off

**Comment by muneeb2542** [comment]
All the changes that were required and all the issues the @affan00 described to me are fixed now.So I'm assigning this issue back to him so he can give the final touches.

**Comment by affan00** [comment]
done, deployed
