### ISSUE TITLE
Add duration to /archives tab ? (finish time - start time)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1086]
If you can do this easily, it would be nice.

**Comment by muneeb2542** [comment]
Marco,we are already displaying the from and to time of the clip in the table.Which kinda serves the same purpose.

But if you want exact time(finish time  - start time) of the clip displayed that can be done also.

**Comment by marcoherbst** [comment]
Yes, I do.

I think " 1hr 14 mins" is helpful info, even though, if I was Rain Man, 

https://www.youtube.com/watch?v=KKC3W0awjm0

I might not need it. :)

**Comment by muneeb2542** [comment]
That's true :-)

Just implementing this right now.

On 5 April 2016 at 15:34, Marco Herbst <notifications@github.com> wrote:

> Yes, I do.
>
> I think " 1hr 14 mins" is helpful info, even though, if I was Rain Man,
>
> https://www.youtube.com/watch?v=KKC3W0awjm0
>
> I might not need it. :)
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/1086#issuecomment-205749467>
>



-- 


Muneeb-ur-Rehman
Junior Software Developer
Evercam.io

**Comment by muneeb2542** [comment]
Done in #1083
