### ISSUE TITLE
Improve the design of offline status in camera list

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#1097]
I am trying to make the design on mobile consistent with web dashboard, and there are improvements should be made before applying it to Android and iOS.

This is how they currently look like:
Dashboard: <img width="407" alt="screen shot 2016-04-07 at 17 19 08" src="https://cloud.githubusercontent.com/assets/5046761/14358639/c93d712c-fce5-11e5-9dbb-a3e4c06d34c5.png">
Android: ![screen shot 2016-04-07 at 17 25 36](https://cloud.githubusercontent.com/assets/5046761/14358640/c96a66a0-fce5-11e5-8da6-c8dfb105af28.png)

Here are some thoughts:
- Use the same offline image, the one we use in dashboard looks better (it's returned by the thumbnail endpoint from media server). But there is a long message that can barely be seen on Android when it's two cameras per row, like this:

<img width="280" alt="screen shot 2016-04-07 at 16 57 58 copy" src="https://cloud.githubusercontent.com/assets/5046761/14358530/476363e6-fce5-11e5-90f9-1a7f120f4fa9.png">
- We are adding a dark color overlay on the thumbnail image if the camera is offline. But if the camera doesn't have a valid thumbnail, the thumbnail endpoint returns 404 with the offline icon, by displaying the offline icon, it's clear enough that the camera is offline and there is no need to add the dark overlay. (Plus there is a gradient background under the camera name text, which makes it even darker. The gradient background is only useful in case the camera name text mix up with a white background)

So things to be done are:
- [ ] Remove the long message from the offline image and make the icon bigger
- [x] Remove the overlay if camera doesn't have a valid thumbnail image (or keep the overlay but remove the gradient background in this situation)

Let me know if there are any better suggestions. When this is done then I'll create issues for Android and iOS.

**Comment by affan00** [comment]
@liutingdu the offline image is being set straight from media and the dash might become a bit slow if changed it on the front end.What I can do is make the required image,so it can be changed straight from media.

**Comment by marcoherbst** [comment]
@affan00  , this is quite a fun task. It will require designing a better image for camera offline. It might also mean designing several different images for different sorts of offline scenarios. I've got ideas for this, but my ideal scenario is that someone (you?) would initiate this and then we could work on it together. 

Yes the image comes from Evercam-Media, but don't be nervous of that, @mosic will be delighted to collaborate.

Qs 
What resolution / aspect ratio ?
Must it be a jpeg or could we use svg ?
Just one version? or different ones for different types of offline? (with different messages) ?
... all in all, see what thoughts you have. 

My idea was to make something kind of fun, based on these images:
https://www.google.ie/search?q=tv+test+card+image&espv=2&biw=1920&bih=979&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjn58CRkP_LAhXGmR4KHQR-AuEQ_AUIBigB#tbm=isch&tbs=rimg%3ACUKo6taHGpGNIjh30uR4laOXFgRhVCATielrqbQEBOPfxGZq0Y3rTbj9XJwhjJ95BVer5os7wkaaVOwiQb_1pcsDJayoSCXfS5HiVo5cWET2CZYNnr5qiKhIJBGFUIBOJ6WsRMEuvFdhMHUoqEgmptAQE49_1EZhEOai3BbFprOCoSCWrRjetNuP1cEesTaD19LfqwKhIJnCGMn3kFV6sRnEje3nrAoSwqEgnmizvCRppU7BGfWUl4ji58bioSCSJBv-lywMlrEdUagVwZ72QF&q=tv%20test%20card%20image

@mosic , you might throw your tuppence in here?

**Comment by mosic** [comment]
The most important thing to me is that the image is useful to the end user, so it needs to have clear message on it.

Different versions - yes, we also need a default image for a newly created camera that doesn't have any snapshots or a thumbnail yet.

It would be nice for the message to be in a square even if we decide to use a wide aspect ratio, so we can show it cropped if needed.

We need to use jpg in order to work seamlessly. Anything else would just complicate all parts of the system.

**Comment by marcoherbst** [comment]
@liutingdu  are you satisfied if affan just uses our existing -media image, but make some changes to get more like the android app as you've suggested (shading, transparency, etc. ).

that would be a step forwards, right?

**Comment by liutingdu** [comment]
@marcoherbst Yes I'll make the changes on Android and see how it works. The only concern is the text would be too small on mobile

**Comment by marcoherbst** [comment]
Great, then do it and we'll worry about that problem when it happens. Nice
one.

On 8 April 2016 at 15:14, Liuting Du <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> Yes I'll make the changes
> on Android and see how it works. The only concern is the text would be too
> small on mobile
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/1097#issuecomment-207447453>
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by affan00** [comment]
done and create the new issue for making the new image.

**Comment by liutingdu** [comment]
I've done it on Android as well and this is how it looks like:

<img width="350px "src="https://cloud.githubusercontent.com/assets/5046761/14461689/906235a2-00bb-11e6-9186-06e4fed51f31.png">

I'll create an issue for iOS to make the same change.
