### ISSUE TITLE
Issues in offline camera live view screen

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#1098]
- [x] Refresh button shouldn't disappear on smaller screen (see the first screenshot)
- [x] Use the same refresh button as used in offline camera thumbnail.
- [x] The offline test shouldn't overlap with text in the image (see the first screenshot), this issue could have been solved in https://github.com/evercam/evercam-dashboard/issues/1097
- [ ] The offline image shouldn't be scaled (see the second screenshot)

<img width="401" alt="screen shot 2016-04-07 at 16 49 43" src="https://cloud.githubusercontent.com/assets/5046761/14357572/1d58c7e8-fce1-11e5-8a07-95e2dd8aec57.png">
<img width="804" alt="screen shot 2016-04-07 at 16 51 26" src="https://cloud.githubusercontent.com/assets/5046761/14357573/1d5a04a0-fce1-11e5-9ae0-2aca18920b24.png">

**Comment by affan00** [comment]
@liutingdu for step#4 offline image shouldn't be scaled, As our each image is maintaining our aspect ratio according to the height of the window if I remove the scaling of the offline image then I need to make many changes in other src of the placeholders and it will disturb the aspect ratio.

**Comment by affan00** [comment]
its fixed and live now.
