### ISSUE TITLE
Archive table changes.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#1111]
- [x] "Create Clip" does not work responsively.
- [x] Remove the "!" from the tool tip text (next use ! if you can avoid it).
- [x] fix broken thing in screenshot
- [x] On Add a camera page fix input field "camera name" of max 24 characters.

![screenshot-dash evercam io 2016-04-14 09-20-24](https://cloud.githubusercontent.com/assets/6482077/14522419/e505cc44-0247-11e6-8eb0-dae8b8f036cc.png)

**Comment by affan00** [comment]
it's done
