### ISSUE TITLE
[Airbrake] [Production] Network is unreachable - connect(2) for "freegeoip.net" port 80

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1118]
**Airbrake error:** [#8671](https://evercam.airbrake.io/projects/98599/groups/1664397210937358671)
**Airbrake project:** Evercam Dashboard

**Error type:** `Errno::ENETUNREACH`
**Error message:** `` Network is unreachable - connect(2) for "freegeoip.net" port 80 ``
**Where:** `users#new`
**Occurred at:** Apr 15, 2016 10:20:08 UTC
**First seen at:** Apr 15, 2016 10:20:08 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/users/signup?key=80cd5243b248aef09429e2a18a859ad2d384a300534d6640b1](https://dash.evercam.io/v1/users/signup?key=80cd5243b248aef09429e2a18a859ad2d384a300534d6640b1)
**File:** `[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb`

**Backtrace:**
```
[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in initialize
[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in open
[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:879:in block in connect
[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:88:in block in timeout
```

**Comment by muneeb2542** [comment]
this irrelevant now.
