### ISSUE TITLE
[Airbrake] [Production] undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1122]
**Airbrake error:** [#7197](https://evercam.airbrake.io/projects/98599/groups/1667081460346157197)
**Airbrake project:** Evercam Dashboard

**Error type:** `NoMethodError`
**Error message:** `` undefined method `each' for nil:NilClass ``
**Where:** `invoices#show`
**Occurred at:** Apr 19, 2016 03:13:15 UTC
**First seen at:** Apr 19, 2016 03:13:15 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/users/mocierion/billing/invoices/in_17w1SGGsHUwFb0QlBirvETdP](https://dash.evercam.io/v1/users/mocierion/billing/invoices/in_17w1SGGsHUwFb0QlBirvETdP)
**File:** `[PROJECT_ROOT]/app/views/shared/_sidebar.html.erb`

**Backtrace:**
```
[PROJECT_ROOT]/app/views/shared/_sidebar.html.erb:25:in _app_views_shared__sidebar_html_erb___616087497834353487_69913916736540
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.1/lib/action_view/template.rb:145:in block in render
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in instrument
```

**Comment by muneeb2542** [comment]
Done

**Comment by muneeb2542** [comment]
Now it is done and tested.
