### ISSUE TITLE
Update SSL cert for dashboard.evercam.io

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1127]
We've switched to using dash.evercam.io almost everywhere, but dashboard.evercam.io still needs a valid cert in order for redirects to work properly.

**Comment by marcoherbst** [comment]
Ah ! That's it . Nice one.

@ijunaidfarooq  ... that'll be what got me this morning. 

@mosic out of interest, how did you realise?

m

**Comment by mosic** [comment]
@marcoherbst I was trying to figure out why the recordings interface wasn't working in the mobile apps: https://github.com/evercam/evercam-play-android/issues/167

**Comment by ijunaidfarooq** [comment]
Certs have been uploaded to [dashboard.evercam.io](https://dashboard.evercam.io). And They are uploaded at `CloudFront` which is slightly different from `AWS Elastic Beanstalk` So I have updated the [Adding SSL](https://github.com/evercam/evercam-api/wiki/Adding-SSL) Document.
