### ISSUE TITLE
Put some settings in the left nav bar? 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1134]
e.g. online/offline, cams / row, refresh & refresh interval

I'm talking about the green box area in this image

- [x] move online offline cameras toggle in the setting submenu and instead of using toggle use checkbox.
- [x] make font size smaller
- [x] reduce the vertical height of the central tab.

![screenshot-dash evercam io 2016-04-20 13-17-35](https://cloud.githubusercontent.com/assets/5648894/14674187/b19f5f34-06fa-11e6-9d80-be6728ca81bc.png)

**Comment by marcoherbst** [comment]
Bad spec. More in email chat. Search for "bad-spec-settings-nav" :)

**Comment by affan00** [comment]
done
