### ISSUE TITLE
Change position of recording settings ....

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1135]
Currently they are below the calendar on /recordings

Problem 1: They are too easy to accidentally change
Problem 2: They take up too much horizontal space, especially when we are able to show/hide the calendar.

Suggestion:
Put them at the bottom of the page.  (solves problem 2)
2 modes ... one to show the recording settings and a button to edit them which creates a pop-up where we can edit all the settings ... same as how we edit a camera details.

Seem ok?

**Comment by affan00** [comment]
This issue is already completed and will be deployed along with the issue https://github.com/evercam/evercam-dashboard/issues/1076.

**Comment by affan00** [comment]
closing this now
