### ISSUE TITLE
Space optimisations on live view page

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1137]
Can you get rid of the wasted spaces in the green boxes ?and aggressively reduce the vertical height of the tabs ? (by, like, 50% ?)

![screenshot-dash evercam io 2016-04-20 20-46-57](https://cloud.githubusercontent.com/assets/5648894/14688271/b9548774-0739-11e6-8731-6a3ada107e66.png)

**Comment by affan00** [comment]
reduced the vertical height of the tab like 30%.
remove the extra space between live view and sidebar. 
reduce the extra space below the live view as possible further reduction disturb the alignment.
