### ISSUE TITLE
For read-only shares, add a delete icon to top right corner 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1138]
This deletes the share.

![screenshot-dash evercam io 2016-04-20 21-22-26](https://cloud.githubusercontent.com/assets/5648894/14689213/49ddf790-073e-11e6-8a51-a8812683a99f.png)

For full-rights and owned cameras, this button will be a settings button which takes you to the settings page. (You dont need to do that now, we can tackle it later).

The settings page will be a new improved version of the current details page.

**Comment by affan00** [comment]
done
