### ISSUE TITLE
[Airbrake] [Production] Your card was declined.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1143]
**Airbrake error:** [#0232](https://evercam.airbrake.io/projects/98599/groups/1669956067008870232)
**Airbrake project:** Evercam Dashboard

**Error type:** `Stripe::CardError`
**Error message:** `` Your card was declined. ``
**Where:** `payments#create`
**Occurred at:** Apr 23, 2016 02:24:36 UTC
**First seen at:** Apr 23, 2016 02:24:36 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/payments](https://dash.evercam.io/v1/payments)
**File:** `[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/bundler/gems/stripe-ruby-d6dc78d5ce1e/lib/stripe.rb`

**Backtrace:**
```
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/bundler/gems/stripe-ruby-d6dc78d5ce1e/lib/stripe.rb:260:in handle_api_error
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/bundler/gems/stripe-ruby-d6dc78d5ce1e/lib/stripe.rb:143:in rescue in request
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/bundler/gems/stripe-ruby-d6dc78d5ce1e/lib/stripe.rb:129:in request
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/bundler/gems/stripe-ruby-d6dc78d5ce1e/lib/stripe/api_operations/request.rb:15:in request
```

**Comment by muneeb2542** [comment]
The problem was also fixed in #1144 
So it is irrelevant now.

Closing this
