### ISSUE TITLE
Sign in and sign up video not playing on ios devices

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1182]
(NB ... I notice it doesn't play on iPad .... not urgent.  My guess is because you need HLS option to work on safari)

**Comment by marcoherbst** [comment]
@affan00 , is this something we could ask @Zulqarnain-Mustafa to look after? He's now much more familiar with video formats etc. If so, discuss & re-assign.

**Comment by affan00** [comment]
Used proper video formats (WebM, mp4 & ogv) those are compatible with most browsers & declared CSS rules in CSS file instead of CoffeeScript.
