### ISSUE TITLE
[Airbrake] [Production] bad URI(is not URI?): /v1/cameras/hikvision ds-2cd8133f-e.json

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1198]
**Airbrake error:** [#1083](https://evercam.airbrake.io/projects/98599/groups/1683891434850251083)
**Airbrake project:** Evercam Dashboard

**Error type:** `URI::InvalidURIError`
**Error message:** `` bad URI(is not URI?): /v1/cameras/hikvision ds-2cd8133f-e.json ``
**Where:** `cameras#single`
**Occurred at:** May 12, 2016 07:52:55 UTC
**First seen at:** May 12, 2016 07:52:55 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/cameras/hikvision%20ds-2cd8133f-e](https://dash.evercam.io/v1/cameras/hikvision%20ds-2cd8133f-e)
**File:** `[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/uri/generic.rb`

**Backtrace:**
```
[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/uri/generic.rb:1100:in rescue in merge
[PROJECT_ROOT]/vendor/ruby-2.2.4/lib/ruby/2.2.0/uri/generic.rb:1097:in merge
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:406:in build_exclusive_url
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:192:in build_env
```

**Comment by marcoherbst** [comment]
@muneeb2542  ... is this simply a type on the Model-ID that we need to change? If so, quick fix?

**Comment by muneeb2542** [comment]
It's not because of any request we use.I recreated this error and found
that somebody had intentionally write the above url on the browser.That is
why the error arose.

I will close this issue because it is irrelavant now

On 20 May 2016 at 12:36, Marco Herbst <notifications@github.com> wrote:

> @muneeb2542 <https://github.com/muneeb2542> ... is this simply a type on
> the Model-ID that we need to change? If so, quick fix?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/1198#issuecomment-220538211>
>



-- 


Muneeb-ur-Rehman
Junior Software Developer
Evercam.io

**Comment by muneeb2542** [comment]
Closing this
