### ISSUE TITLE
[Airbrake] couldn't find file 'datetimepicker/jquery.datetimepicker.js' with type 'application/javascript'

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1206]
**Airbrake error:** [#0119](https://evercam.airbrake.io/projects/98599/groups/1686792140242450119)
**Airbrake project:** Evercam Dashboard

**Error type:** `ActionView::Template::Error`
**Error message:** `` couldn't find file 'datetimepicker/jquery.datetimepicker.js' with type 'application/javascript' ``
**Where:** `cameras#index`
**Occurred at:** May 16, 2016 07:56:16 UTC
**First seen at:** May 16, 2016 07:56:16 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [http://localhost:3000/v1/cameras](http://localhost:3000/v1/cameras)
**File:** `/home/maestro/evercam/evercam-dashboard/app/assets/javascripts/snapshot_navigator_widget.js`

**Backtrace:**
```
/home/maestro/evercam/evercam-dashboard/app/assets/javascripts/snapshot_navigator_widget.js:16:in 
[GEM_ROOT]/gems/sprockets-3.6.0/lib/sprockets/resolve.rb:64:in resolve!
[GEM_ROOT]/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:399:in resolve
[GEM_ROOT]/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:207:in process_require_directive
...
Caused by Sprockets::FileNotFound: couldn't find file 'datetimepicker/jquery.datetimepicker.js' with type 'application/javascript'
```

**Comment by muneeb2542** [comment]
I have updated airbrake gem, that is why the errors displayed in development environment were also being displayed.So I have specified airbrake to show only production errors.

This is irrelevant now
