### ISSUE TITLE
[Airbrake] undefined method `interval' for false:FalseClass

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1220]
**Airbrake error:** [#8687](https://evercam.airbrake.io/projects/98599/groups/1688426166254468687)
**Airbrake project:** Evercam Dashboard

**Error type:** `NoMethodError`
**Error message:** `` undefined method `interval' for false:FalseClass ``
**Where:** `invoices#show`
**Occurred at:** May 18, 2016 14:02:47 UTC
**First seen at:** May 18, 2016 14:02:47 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/users/admin_bsg/billing/invoices/in_189yArGsHUwFb0QlUx1ZUgDE](https://dash.evercam.io/v1/users/admin_bsg/billing/invoices/in_189yArGsHUwFb0QlUx1ZUgDE)
**File:** `/app/app/views/invoices/show.html.erb`

**Backtrace:**
```
/app/app/views/invoices/show.html.erb:13:in _app_views_invoices_show_html_erb__3702278734296616812_69886942069480
[GEM_ROOT]/gems/actionview-4.2.6/lib/action_view/template.rb:145:in block in render
[GEM_ROOT]/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in block in instrument
[GEM_ROOT]/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in instrument
```

**Comment by muneeb2542** [comment]
This issue is in reference to #1224 which is fixed now.

Closing this
