### ISSUE TITLE
Add new column in logs datatable.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1225]
- [x] give me a new column with a link to recordings at that date/time , just an icon can link there ( image icon ? image + clock ?) 

- [x] Also, we have "created" as an event ... I think that's silly. Instead, let's show the created date of camera, somehow nicely and remove this as a tickbox ... programmatically it can always be ticked (don't show it, but always include it).

the icon could have a popup thumbnail of the recording ? use http://fontawesome.io/icon/picture-o/.

**Comment by affan00** [comment]
This task is mostly related to back-end work so I am assigning this to Muneeb and when Muneeb completes it's backend work, I will complete its front-end related work.

**Comment by muneeb2542** [comment]
@mh do you want a thumbnail in the new column for that time provided or an icon that takes you to the recordings at that time in the recordings tab?

**Comment by marcoherbst** [comment]
Settle for either. I like the thumbnail by preference though. (Small).


On 8 June 2016 at 11:19, Muneeb Rana <notifications@github.com> wrote:

> @mh <https://github.com/mh> do you want a thumbnail in the new column for
> that time provided or an icon that takes you to the recordings at that time
> in the recordings tab?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/1225#issuecomment-224548709>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFYx_q5Oaetxa3CJBAd0RFgefuM36Ymcks5qJpc7gaJpZM4IiKwA>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
The backend work for this issue is complete,So I'm assigning this issue back to Affan he will finish with styling work and deploy it

**Comment by marcoherbst** [comment]
@muneeb2542  ... seems to me that this is currently assigned to @muneeb2542 and I don't see why it's in this milestone. Chaps ?

**Comment by muneeb2542** [comment]
it's here because i'm using an endpoint which was making the log page very slow,So i consulted with Milos on it and he said this same endpoint is going to be very fast after 2 to 3 weeks so wait for it.

**Comment by muneeb2542** [comment]
Otherwise the code is complete and when the shift to media will complete i will deploy it asap.

**Comment by muneeb2542** [comment]
Done

**Comment by marcoherbst** [comment]
Technically complete, but far too ugly. Don't use the actual thumbnail in the list, use the fa icon that we discussed. Put it in column 1. Make it 16*16. Don't have a column title or sort by option.

**Comment by muneeb2542** [comment]
I have removed the extra column for thumbnails and added the fa-icon in column 1.Now on hover of the icon, you will see the thumbnail for that time period.

So Closing this
