### ISSUE TITLE
Show camera recording status in the left nav

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1229]
Let's do it with a single, flashing red pixel to the left of the camera name in the navigation.
Bringing this into Feb.

**Comment by muneeb2542** [comment]
@marcoherbst  the camera object we are using to display the names in the sidebar does not contain cloud recordings in it and currently we don't have any endpoint which gives us cloud recording of all the cameras of the user.Without it,it would be impossible fetch all CRs in a list and display small icons for recordings.

We would need an endpoint like this to complete the job
Get  /cameras/{**user_id**}/apps/cloud-recording

**Comment by marcoherbst** [comment]
@muneeb2542 is this still waiting on a -media endpoint ? If it is, could you please create the issue on media and make the connection between the issues.

**Comment by marcoherbst** [comment]
@affan00 NB I brought this back to life - try it with just a single red pixel. It might be ok.

**Comment by affan00** [comment]
Added the flashing green pixel to the left of the recording camera name in the sidebar.
I am closing this now.
