### ISSUE TITLE
Geolocation error when adding a new user

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#1234]
whenever a new user is created its location is automatically set via geocoder gem but after applying SSL cert its location fetching function is not working properly.

Find a way to make it work with SSL.

**Comment by affan00** [comment]
This issue is not valid now, We are not saved user location when a new user is created. I also test it after creating a new user but it doesn't give any geolocation error on console.

**Comment by affan00** [comment]
Fixed the error and successfully got new user location (country) using geocoder gem and autofill its value on creating a new account, it's done so I am closing this now.
