### ISSUE TITLE
When i only have 1 or 2 cameras, use the space better

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1235]
For 1 camera, how about defaulting to the /camera/live page 

For 2 cameras, how about using a 2 column layout.

... My hunch is that there are more scenarios, but this seems like 2 quick fixes to handle the most common cases.

**Comment by marcoherbst** [comment]
@affan00  , I think this is well enough spec'd , unless you see any problems.

**Comment by affan00** [comment]
It's done.
