### ISSUE TITLE
Settings/Cameras Table

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1236]
A table which shows me all my cameras (owned & shared with me), in a report like: https://admin.evercam.io/cameras

Can I have a v1 which includes all the info that it is easy to put in there .... should include Cloud Recordings.  .... We will need to iterate, so let's just start with what's easy and work from there.

Admin datatable format is nice, I would say.

**Comment by affan00** [comment]
It's done and deployed.
