### ISSUE TITLE
[Airbrake] username is invalid

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1242]
**Airbrake error:** [#2329](https://evercam.airbrake.io/projects/98599/groups/1693842958330262329)
**Airbrake project:** Evercam Dashboard

**Error type:** `Sequel::ValidationFailed`
**Error message:** `` username is invalid ``
**Where:** `users#password_reset_request`
**Occurred at:** May 26, 2016 01:25:14 UTC
**First seen at:** May 26, 2016 01:25:14 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/users/password-reset](https://dash.evercam.io/v1/users/password-reset)
**File:** `[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/model/base.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/model/base.rb:1543:in save
[GEM_ROOT]/gems/newrelic_rpm-3.15.2.317/lib/sequel/plugins/newrelic_instrumentation.rb:30:in block (3 levels) in wrap_sequel_method
[GEM_ROOT]/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent.rb:431:in disable_all_tracing
[GEM_ROOT]/gems/newrelic_rpm-3.15.2.317/lib/sequel/plugins/newrelic_instrumentation.rb:30:in block (2 levels) in wrap_sequel_method
```

**Comment by muneeb2542** [comment]
This was a validation error of the account and has nothing related to password not reseting.
For reference #1245
