### ISSUE TITLE
[Airbrake] PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1250]
**Airbrake error:** [#4906](https://evercam.airbrake.io/projects/98599/groups/1695177248624244906)
**Airbrake project:** Evercam Dashboard

**Error type:** `Sequel::DatabaseDisconnectError`
**Error message:** `` PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly ``
**Where:** `cameras#index`
**Occurred at:** May 27, 2016 21:36:20 UTC
**First seen at:** May 27, 2016 21:36:20 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/cameras](https://dash.evercam.io/v1/cameras)
**File:** `[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/adapters/postgres.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/adapters/postgres.rb:180:in async_exec
[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/adapters/postgres.rb:180:in block in execute_query
[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/database/logging.rb:33:in log_yield
[GEM_ROOT]/gems/newrelic_rpm-3.15.2.317/lib/sequel/extensions/newrelic_instrumentation.rb:45:in block in log_yield
...
Caused by PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly

Caused by Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly
```

**Comment by muneeb2542** [comment]
This is also irrelevant now, for reference #1251 

Closing this
