### ISSUE TITLE
[Airbrake] could not translate host name "ec2-52-50-58-246.eu-west-1.compute.amazonaws.com" to address: Name or service not known

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1251]
**Airbrake error:** [#7035](https://evercam.airbrake.io/projects/98599/groups/1696504153025707035)
**Airbrake project:** Evercam Dashboard

**Error type:** `PG::ConnectionBad`
**Error message:** `` could not translate host name "ec2-52-50-58-246.eu-west-1.compute.amazonaws.com" to address: Name or service not known ``
**Where:** `<no information>`
**Occurred at:** May 29, 2016 17:32:41 UTC
**First seen at:** May 29, 2016 17:32:41 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/](https://dash.evercam.io/)
**File:** `[GEM_ROOT]/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in initialize
[GEM_ROOT]/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in new
[GEM_ROOT]/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in connect
[GEM_ROOT]/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in initialize
```

**Comment by muneeb2542** [comment]
This is irrelevant now.It happened due to maintanence of our DB,due to which the connection was lost for short time(15 min).

Closing this
