### ISSUE TITLE
Show an informative Sharing Tab for Read-Only users

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1254]
We'd like to have the Sharing tab for Read-Only users.

Use this text:

*********************************************

You have **Read Only** access to this **private** camera.

In order to share this camera with other people, it must either be a **public camera** or you must have Full Rights to share.

If you would like to share this camera, please request **Full Rights** access from the owner, **Marco Herbst** marco@evercam.io or contact Evercam Support.

With Evercam, it is possible to share your camera with as many people as you wish. 

Go ahead, share the love !

*********************************************

**Comment by marcoherbst** [comment]
@vinnieq ... this is my current spec for this. You might have other ideas.

**Comment by marcoherbst** [comment]
[ Request Full-Rights]
---

NB1. This will require a new endpoint "Rights Request"

NB2. This is a perfect example of where "Follow" deviates from Read Only. In a Follow scenario, it is perfectly ok for me to share a public camera with anyone else, it's more like "Recommend this camera to a friend".
---

**Comment by marcoherbst** [comment]
@affan00  I simplified this task by removing the requirement for an endpoint, now I think you can do the whole task yourself, right?

**Comment by affan00** [comment]
@marcoherbst yes,

**Comment by affan00** [comment]
It's done, Live now.
