### ISSUE TITLE
Last Login not working

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-dashboard#1256]
Currently, it's not working. Implement the Last Login with UTC Timestamp.

@muneeb2542 have a look on this issue.

@Zulqarnain-Mustafa you may also need to apply this to IOS app & Android App as well. As this is the client based thing. When User will login then it will update `Time.now` of the user in UTC.

**Comment by muneeb2542** [comment]
This feature is now added to dashboard and it's working fine.

Closing this
