### ISSUE TITLE
Dropdown on live view widget to include thumbnails.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1264]
If this means designing a new endpoint, don't fear that. Open the discussion.

**Comment by marcoherbst** [comment]
get thumbnails from browser cache ?

I'll move this into the future.

**Comment by marcoherbst** [comment]
@affan00  , if you believe this can be done with no negative side-effects in terms of speed or overloading bandwidth or browser, then go ahead. This task is 90% about how you do it ... if it is done to the detriment of performance, then it is better not to do it at all.

**Comment by affan00** [comment]
It's done.
