### ISSUE TITLE
Use Domain Favicons as fallbacks to Gravatars

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1266]
This kind of idea: https://github.com/seveas/davatar/blob/master/davatar.py

I think:
1. Try Gravatar
2. Else, try Domain Favicon
3. Else, use Gravatar Fallback.

Please forgive my newbie functional code.

**Comment by muneeb2542** [comment]
This issue is done will make another one later for it's improvement.

Closing this
