### ISSUE TITLE
[Airbrake] 501 Recipient syntax error

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1270]
**Airbrake error:** [#1280](https://evercam.airbrake.io/projects/98599/groups/1701918386030801280)
**Airbrake project:** Evercam Dashboard

**Error type:** `Net::SMTPSyntaxError`
**Error message:** `` 501 Recipient syntax error ``
**Where:** `sharing#resend_share_request`
**Occurred at:** Jun 06, 2016 04:49:48 UTC
**First seen at:** Jun 06, 2016 04:49:48 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/share/request/resend](https://dash.evercam.io/share/request/resend)
**File:** `/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb`

**Backtrace:**
```
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:965:in check_response
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:934:in getok
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:870:in rcptto
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:851:in block in rcptto_list
```

**Comment by muneeb2542** [comment]
It happened due to some changes while testing and which were fixed.

This is irrelevant now.
