### ISSUE TITLE
Current implementation of avatars on sharing tab is slow and blocks page rendering

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1293]
My suggestion is to lookup and save the images for all accounts, and use it in future requests instead of requesting it again for every page load.

Or, at least move the lookup on the client side, so it doesn't block the page load (for `centralbankbuild` camera it took 7 seconds just to lookup the avatars).

**Comment by marcoherbst** [comment]
@muneeb2542 there should be no performance impact allowable on first loading of the page. If there is, remove this feature until that is fixed. Sorry, should have made that clear.

My bias is towards Milos' second suggestion.

What would Mega.co.nz do? that's the fastest app I know.

**Comment by muneeb2542** [comment]
@mh I will look into improving its performance right now.If it takes too much time today I will disable the feature and will search for an improvement then.

**Comment by muneeb2542** [comment]
Gravatar and it's fallback implementation is now shifted to the client side and it is working fine.

Closing this.
