### ISSUE TITLE
Cameras with a timezone offset that doesn't round up to an hour aren't handled correctly

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1295]
I noticed this problem with the `premierinfo_2018` camera. It has a timezone offset of UTC+05:30, but the snapshot navigator interface displays it as if it's UTC+06:00.

Quick glance at the snapshot navigator code makes me believe that this is the cause of the bug: [snapshots_navigator.js.coffee#L320-L328](https://github.com/evercam/evercam-dashboard/blob/ff14b2ab45b6733aa12512d8386ae8350ff077a8/app/assets/javascripts/cameras/single/snapshots_navigator.js.coffee#L320-L328)

Btw keep in mind that there are even more unusual timezones, with offsets like UTC+05:45: https://en.wikipedia.org/wiki/List_of_UTC_time_offsets

**Comment by muneeb2542** [comment]
Done
