### ISSUE TITLE
[Airbrake] [Production] No user details specified in request.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1305]
**Airbrake error:** [#3439](https://evercam.airbrake.io/projects/98599/groups/1712143692217873439)
**Airbrake project:** Evercam Dashboard

**Error type:** `RuntimeError`
**Error message:** `` No user details specified in request. ``
**Where:** `<no information>`
**Occurred at:** Jun 20, 2016 07:26:17 UTC
**First seen at:** Jun 20, 2016 07:26:17 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [http://test.host/users](http://test.host/users)
**File:** `/home/travis/build/evercam/evercam-dashboard/app/controllers/users_controller.rb`

**Backtrace:**
```
/home/travis/build/evercam/evercam-dashboard/app/controllers/users_controller.rb:53:in create
[GEM_ROOT]/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:4:in send_action
[GEM_ROOT]/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in process_action
[GEM_ROOT]/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in process_action
```

**Comment by muneeb2542** [comment]
This was due to tests performed in travis.

So they are irrelevant now.
