### ISSUE TITLE
[Airbrake] [Production] 501 Recipient syntax error

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1322]
**Airbrake error:** [#7898](https://evercam.airbrake.io/projects/98599/groups/1718197340072997898)
**Airbrake project:** Evercam Dashboard

**Error type:** `Net::SMTPSyntaxError`
**Error message:** `501 Recipient syntax error`
**Where:** `sharing#resend_share_request`
**Occurred at:** Jun 28, 2016 15:54:15 UTC
**First seen at:** Jun 28, 2016 15:54:15 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/share/request/resend](https://dash.evercam.io/share/request/resend)
**File:** `/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb`

**Backtrace:**

```
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:965:in check_response
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:934:in getok
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:870:in rcptto
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:851:in block in rcptto_list
```

**Comment by marcoherbst** [comment]
*Comment from Airbrake:* Resolved [error](https://evercam.airbrake.io/projects/98599/groups/1718197340072997898) reoccurred.

**Comment by muneeb2542** [comment]
This error hasn't occurred again in a long time.Plus I have tested the link for which this happened and the link is working fine now.

So I'm closing this

**Comment by marcoherbst** [comment]
*Comment from Airbrake:* Resolved [error](https://evercam.airbrake.io/projects/98599/groups/1718197340072997898) reoccurred.
