### ISSUE TITLE
[Airbrake] [Production] undefined method `zero?' for nil:NilClass

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1330]
**Airbrake error:** [#3296](https://evercam.airbrake.io/projects/98599/groups/1720327379124123296)
**Airbrake project:** Evercam Dashboard

**Error type:** `NoMethodError`
**Error message:** `` undefined method `zero?' for nil:NilClass ``
**Where:** `public#index`
**Occurred at:** Jul 01, 2016 14:26:21 UTC
**First seen at:** Jul 01, 2016 14:26:06 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/public/cameras](https://dash.evercam.io/v1/public/cameras)
**File:** `[GEM_ROOT]/gems/yui-compressor-0.12.0/lib/yui/compressor.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:101:in block in compress
[GEM_ROOT]/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:141:in streamify
[GEM_ROOT]/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:86:in compress
[GEM_ROOT]/gems/sprockets-3.6.1/lib/sprockets/yui_compressor.rb:49:in call
```

**Comment by muneeb2542** [comment]
Irrelevant now.
