### ISSUE TITLE
Video.JS update from 4.x to 5.x

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1335]
Not sure if this improves things, but it might. Especially if we're trying to maximise compatibility.

**Comment by marcoherbst** [comment]
I'm putting this in a more urgent milestone and assigning it to Affan.

Affan, I expect this to cause a few problems esp if we've made any customisation, but, the player is a pretty important thing for us and we should stay current. Good luck with ti.

**Comment by marcoherbst** [comment]
When completed, do a quick check to see what works for http://www.carrollsirishgifts.com/livedublinwebcam

Android:
 + Default Browser
 + Chrome

iOS
 + Safari

Desktop
 + IE11
 + IE Edge
 + Firefox (w/o Flash)
 + Firefox w/ Flash
 + Chrome

**Comment by affan00** [comment]
Not working fine in ie11, it's layout issues.

**Comment by affan00** [comment]
It's fixed and deployed.
