### ISSUE TITLE
Use snapshot days endpoint to fill out the days in the calendar

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1336]
When we had issues with query speed on the queries used by the calendar, I made a quick change to check each day in a month separately instead of going through the whole month. This had a couple of benefits:
- the individual queries would take much less time and had less chance of timing out
- they were easier to cache and re-request if the first request failed
- they were shown on the calendar as they were being checked, so the user saw that we were loading data

Now that we're using seaweedfs I reimplemented the endpoint and it's as fast to check one day as it is for whole month, so there is no strong reason to keep using this method, we can go back to using "days" endpoint.

**Comment by marcoherbst** [comment]
@ijunaid8088  .... you're aware of this ?

**Comment by ijunaid8088** [comment]
@marcoherbst Nope I wasn't I just saw that.. 

But I already knew about this endpoint..

**Comment by ijunaid8088** [comment]
Right now there is a bug in
`get "/cameras/:id/recordings/snapshots/:year/:month/days", SnapshotController, :days`

I checked for a camera.. while getting recording days with above endpoint. I just give me all days of the month. Including those which are present or not!

where if I check with 
`get "/cameras/:id/recordings/snapshots/:year/:month/:day", SnapshotController, :day`

It shows correct details that those days don't exist.

**Comment by ijunaid8088** [comment]
Issue added in https://github.com/evercam/evercam-media/issues/537

**Comment by ijunaid8088** [comment]
For follow up:
https://github.com/evercam/evercam-server/issues/537
This bug is fixed now. and we can use days endpoint, to fill days in calendar instead of using single day endpoint to send a request for each day.

**Comment by ijunaid8088** [comment]
its done.
