### ISSUE TITLE
[Airbrake] [Development] undefined method `evercam_api' for #<Rails::Application::Configuration:0x0000000510d830>

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1340]
**Airbrake error:** [#1457](https://evercam.airbrake.io/projects/98599/groups/1727885506266691457)
**Airbrake project:** Evercam Dashboard

**Error type:** `NoMethodError`
**Error message:** `` undefined method `evercam_api' for #<Rails::Application::Configuration:0x0000000510d830> ``
**Where:** `cameras#index`
**Occurred at:** Jul 12, 2016 00:42:21 UTC
**First seen at:** Jul 12, 2016 00:42:21 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [http://localhost:3000/v1/cameras](http://localhost:3000/v1/cameras)
**File:** `[GEM_ROOT][GEM_ROOT]/gems/railties-4.2.6/lib/rails/railtie/configuration.rb`

**Backtrace:**
```
[GEM_ROOT][GEM_ROOT]/gems/railties-4.2.6/lib/rails/railtie/configuration.rb:95:in method_missing
[GEM_ROOT]/home/jack/evercam/evercam-dashboard/app/helpers/application_helper.rb:33:in get_evercam_api
[GEM_ROOT]/home/jack/evercam/evercam-dashboard/app/controllers/application_controller.rb:72:in load_user_cameras
[GEM_ROOT]/home/jack/evercam/evercam-dashboard/app/controllers/cameras_controller.rb:9:in index
```

**Comment by muneeb2542** [comment]
This is a development error,
So irrelevant.

Closing this
