### ISSUE TITLE
Dashboard should automatically update when the user gets a new camera share

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1349]
This should happen when the user follows a public camera, or someone shares a camera with them. Currently they would need to refresh the page to see the new camera.

We can send an event from media using websockets and update cameras on the dashboard, like we do when camera online status changes.

**Comment by marcoherbst** [comment]
Related to : https://github.com/evercam/evercam-dashboard/issues/1500 ?

**Comment by azharmalik3** [comment]
Done.
