### ISSUE TITLE
Setting cloud recording schedule is broken

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1350]
After changing the storage duration for a camera, this is the cloud recordings response I get back:

``` json
{
  "cloud_recordings": [
    {
      "frequency": 60,
      "storage_duration": 90,
      "status": "on",
      "schedule": {
        "Wednesday": [

        ],
        "Tuesday": [

        ],
        "Thursday": [

        ],
        "Sunday": [

        ],
        "Saturday": [

        ],
        "Monday": [

        ],
        "Friday": [

        ]
      }
    }
  ]
}
```

I first thought that this was caused by new endpoints in evercam-media, but sending the request to evercam-api results in the same response.

**Comment by ijunaidfarooq** [comment]
Can be this for a specific camera?

Yesterday everything was wrong fine..

**Comment by mosic** [comment]
I tried it with `gpocam`. If you want to try it, do it in development mode so it doesn't turn off the recordings for the camera.

**Comment by azharmalik3** [comment]
@mosic It's working, not able to replicate this error.

**Comment by mosic** [comment]
@ijunaidfarooq @azharmalik3 It's a real bug, I can replicate it both in development and production.

Steps:
* Open http://localhost:3000/v1/cameras/gpocam/recordings/snapshots/
* Click to edit recording settings
* Change the storage duration to 30
* Click Save

The request parameters sent from the dashboard will be:

```
api_id=...
api_key=...
frequency=60
storage_duration=30
status=on
schedule={"Monday":[],"Tuesday":[],"Wednesday":[],"Thursday":[],"Friday":[],"Saturday":[],"Sunday":[]}
```

**Comment by azharmalik3** [comment]
@mosic I got this issue and will be fixed soon.

**Comment by azharmalik3** [comment]
@mosic i have fixed this issue.
