### ISSUE TITLE
Archive deletion shows an error message on successful request

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1351]
The message comes from this block of code: [evercam-dashboard/archives.js.coffee#L309-L311](https://github.com/evercam/evercam-dashboard/blob/46bbbe06b44a11d0cce92dfe0c40e89da936ce25/app/assets/javascripts/cameras/single/archives.js.coffee#L309-L311)

**Comment by muneeb2542** [comment]
it was a bug with the response returning from evercam-media.It is resolved now

Closing this
