### ISSUE TITLE
[Airbrake] [Production] invalid hash

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1362]
**Airbrake error:** [#1926](https://evercam.airbrake.io/projects/98599/groups/1736440551119681926)
**Airbrake project:** Evercam Dashboard

**Error type:** `BCrypt::Errors::InvalidHash`
**Error message:** `` invalid hash ``
**Where:** `sessions#create`
**Occurred at:** Jul 23, 2016 19:57:24 UTC
**First seen at:** Jul 23, 2016 19:57:24 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/sessions](https://dash.evercam.io/sessions)
**File:** `[GEM_ROOT]/gems/bcrypt-3.1.11/lib/bcrypt/password.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:60:in initialize
[GEM_ROOT]/bundler/gems/evercam-models-b0d5f07cce9d/lib/evercam_models/user.rb:35:in new
[GEM_ROOT]/bundler/gems/evercam-models-b0d5f07cce9d/lib/evercam_models/user.rb:35:in password
/app/app/controllers/sessions_controller.rb:25:in create
```

**Comment by ijunaidfarooq** [comment]
resolved!
