### ISSUE TITLE
[Airbrake] [Production] firstname is invalid

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1363]
**Airbrake error:** [#0838](https://evercam.airbrake.io/projects/98599/groups/1737212475416410838)
**Airbrake project:** Evercam Dashboard

**Error type:** `Sequel::ValidationFailed`
**Error message:** `` firstname is invalid ``
**Where:** `users#confirm`
**Occurred at:** Jul 24, 2016 21:31:04 UTC
**First seen at:** Jul 24, 2016 21:31:04 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/confirm?u=djmaliante&c=e790f9d823ead0de58ab51ce3f278a35c86b58d8](https://dash.evercam.io/confirm?u=djmaliante&c=e790f9d823ead0de58ab51ce3f278a35c86b58d8)
**File:** `[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/model/base.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/sequel-4.26.0/lib/sequel/model/base.rb:1543:in save
[GEM_ROOT]/gems/newrelic_rpm-3.15.2.317/lib/sequel/plugins/newrelic_instrumentation.rb:30:in block (3 levels) in wrap_sequel_method
[GEM_ROOT]/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent.rb:431:in disable_all_tracing
[GEM_ROOT]/gems/newrelic_rpm-3.15.2.317/lib/sequel/plugins/newrelic_instrumentation.rb:30:in block (2 levels) in wrap_sequel_method
```

**Comment by muneeb2542** [comment]
After changing the regex,so this issue is resolved now

Closing this
