### ISSUE TITLE
Encourage people to use capital letters in their names on signup

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1378]
A huge proportion are using small letters.

Sites like Slack are very good at guiding people to not make this mistake. Can we?

M

**Comment by affan00** [comment]
Will be fixed along with this issue so, I am closing this. #1436

**Comment by marcoherbst** [comment]
The reason I don't think these are the same issue is that 1436 is a regex for validating a name whereas this issue is more about prompting / nudging people to do what is more likely to be correct, but that would not force people to spell their name with, for example, a capital letter.

**Comment by marcoherbst** [comment]
This isn't important enough,  and I'm not sure the best way to do it, I'm sending it to the long finger.

**Comment by marcoherbst** [comment]
Meh. Less of an issue these days.
