### ISSUE TITLE
Implement sign up error message.

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-dashboard#1383]
As per discussion fix this issue.

for follow up.. in the sign up 2 things are being checked from API 
1: username
2: email
whether they are taken or not on the dashboard.

The return errors are in this from right now

```
{
  "message": {
    "email": [
      "Email has already been taken."
    ]
  }
}
```

same for the username in case it's taken. Show these messages as they are coming in response! 

You might want to look here first https://github.com/evercam/evercam-dashboard/blob/master/app/controllers/users_controller.rb#L71

**Comment by muneeb2542** [comment]
Done
