### ISSUE TITLE
Archive / Create Clip Interface Improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1398]
- [x] The method of choosing the hour/mins can be improved. Maybe by offering a start time & duration.
- [x] Max duration 30 mins
- [x] When pending, frames is 0. Either tell me the truth or put "Pending"
- [x] Have Create Clip Functionality available on /recordings page (where full rights)
- [x] Fix aspect ratio of thumbnail image in details tab.

**Comment by marcoherbst** [comment]
As mentioned in https://github.com/evercam/evercam-media/issues/294 , maybe we should set a much shorter time limit (30 mins) and ask user to specify just the start time & duration.

**Comment by affan00** [comment]
It's done and deployed.
