### ISSUE TITLE
Repo Management (Homeless)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1416]
These repos can move to Gitlab:
- API
- Faraday
- Public Site
- Models

(Confirm this first with rest of team)

NB, you will need to transfer any relevant Wiki / Issues to the right place.
This might help:
https://github.com/google/github-issue-mover
https://github.com/darwin/move-wiki

**Comment by marcoherbst** [comment]
@azharmalik3 @muneeb2542 @ijunaidfarooq  , could you all have a quick think and see if you agree with this, or if you can advise.

**Comment by affan00** [comment]
Moved to Gitlab and removed from Github.
