### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1418]
When user first-time login give him a welcome message with name i-e ("Welcome Marco") in good layout and when it login again show him message welcome back with name i-e ("Welcome back Marco"). 
@Zulqarnain-Mustafa also related to mobile devices.

**Comment by marcoherbst** [comment]
This is part of user on-boarding, closing.

**Comment by Zulqarnain-Mustafa** [comment]
I agree with you @affan00 and @marcoherbst it is good idea and very user friendly. Hope this will leave a good impact on users.
