### ISSUE TITLE
Improve user on-boarding process

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1419]
@affan00 I've simplified this ticket a little. The process is called user onboarding, you'll find plenty of guides online and libraries on GH.

@Zulqarnain-Mustafa this is also related to mobile.

**Comment by Zulqarnain-Mustafa** [comment]
@affan00 nice idea it should be implemented on mobile side as well. If there can be a cool animated video for user guide it is best.

**Comment by marcoherbst** [comment]
http://introjs.com/ ?

**Comment by marcoherbst** [comment]
@affan00  put a list here of any websites you like or tools you'd like to use ....

**Comment by marcoherbst** [comment]
Closing this too vague
