### ISSUE TITLE
[Airbrake] [Production] Missing template sessions/new, application/new with {:locale=>[:en], :formats=>["image/*"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:   * "/app/app/views"   * "/app/vendor/bundle/ruby/2.3.0/...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1421]
**Airbrake error:** [#1146](https://evercam.airbrake.io/projects/98599/groups/1757870534165691146)
**Airbrake project:** Evercam Dashboard

**Error type:** `ActionView::MissingTemplate`
**Error message:** `Missing template sessions/new, application/new with {:locale=>[:en], :formats=>["image/*"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:   * "/app/app/views"   * "/app/vendor/bundle/ruby/2.3.0/gems/devise-4.2.0/app/views"`
**Where:** `sessions#new`
**Occurred at:** Aug 22, 2016 09:34:55 UTC
**First seen at:** Aug 22, 2016 09:34:55 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/v1/users/signin](https://dash.evercam.io/v1/users/signin)
**File:** `[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/path_set.rb`

**Backtrace:**

```
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/path_set.rb:46:in find
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/lookup_context.rb:121:in find
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:18:in find_template
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:40:in determine_template
```

**Comment by muneeb2542** [comment]
This error is happening due to the rails version we are using and due to the dependencies in our project are not compatible with rails 5 so it is impossible to update it.

This occurrence of this error is very low and it doesn't affect the flow of sign in.So, for now, i'm leaving this and when the gems in dashboard become compatible with rails 5 then I will update the rails version.

**Comment by muneeb2542** [comment]
This error is due to rails version and until the version is upgraded to rails 5 they won't stop and right now the rails 5 in not supported by the dependencies on the project.So I'm leaving this for now and changing it's milestone to long finger.
