### ISSUE TITLE
Travis failed on user sign up test

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-dashboard#1424]
sometimes user signup test fails at first and then on the rebuild of Travis it passes!

Investigate the issue totally, on your local environment by running all tests in development mode.

**Comment by ijunaidfarooq** [comment]
You need to remove those lines

https://github.com/evercam/evercam-dashboard/blob/master/spec/controllers/users_controller_spec.rb#L80-L82

And the test will start passing. 
1: in the test the post request is being sent twice to the same URL with a different type of params.
2: this is not the right way I think to send the params

Maybe am wrong but If you remove those lines and the first request with POST will get you the user with an appropriate status code. I have tested that.

**Comment by muneeb2542** [comment]
Done
