### ISSUE TITLE
Change the cloud recordings so that remain same after turning it off and then on.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#1429]

**Comment by ijunaidfarooq** [comment]
Right now on evercam-media while deletion process, the deletion worker is checking all those cameras whom cloud recordings are not on storage_duration = -1(infinity), and then start deleting the recording for those who are not on Infinity regardless of status on and off.

in the current situation of evercam-dashboard, on CR settings off , the frequency and storage_duration is being set to 1 for both. Which makes the deletion worker.. delete recordings of those cameras also whom recording should not be deleted.

**Comment by marcoherbst** [comment]
Thanks @ijunaidfarooq .
@muneeb2542 close & reference when done.

**Comment by muneeb2542** [comment]
It is deployed now.Forgot to close it.
