### ISSUE TITLE
Broken Html of recordings  when user come from Url.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#1430]
https://dash.evercam.io/v1/cameras/waxie-nvr-2/recordings/snapshots/2016-08-23T08:43:26.000Z

**Comment by affan00** [comment]
When we load the page the width of the recording tab is "0" that's why adjustment has been set on image load and after image processing, all interface loads fine.

**Comment by marcoherbst** [comment]
I'm afraid it's not as simple as that @affan00 

This was repeatable by me and azhar. Azhar, may have screenshots in his inbox, it might be related to resolution.

If you still cant repeat it, close and move on.

**Comment by affan00** [comment]
Not able to replicate it so i am closing this.
