### ISSUE TITLE
show logs with IP

### ISSUE THREAD

**Issue by ijunaid8088** [evercam/evercam-dashboard#1445]
We have added a functionality to log activities for

- Camera Create/Update
- Archive Create/Delete
- CR Create/Update

with an IP address as well. It will be saved in `extra` json object. Also for CR settings You need to show `status`, `storage_duration` & `frequency` which also been saved within `extra` object with an activity text as `cloud recording updated/created` and for the rest it will be only an IP.

**Comment by marcoherbst** [comment]
I don't see why this is not an @affan00  task.

Junaid, all tasks go to @affan00 unless they must go to @muneeb2542 

I've also bumped it to current milestone.

**Comment by affan00** [comment]
It's done and deployed.
