### ISSUE TITLE
Setup Test Coverage % on CC / Travis

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1449]
https://codeclimate.com/github/evercam/evercam-dashboard

and fix on readme.md

(Maybe, if this is a bad idea, let me know)

https://camo.githubusercontent.com/71a5b26de6798405e459d58073cadaaf8690567a/68747470733a2f2f636f6465636c696d6174652e636f6d2f6769746875622f6576657263616d2f6576657263616d2d64617368626f6172642f6261646765732f636f7665726167652e737667

**Comment by muneeb2542** [comment]
It is done now
