### ISSUE TITLE
Public Camera (no share exists) has option to Delete. It shouldn't

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1466]
I clicked on https://dash.evercam.io/v1/cameras/axisc-tdarb

and there is a delete option (top right)., even though I am not an owner or a sharee.

It shouldn't be there. (and it certainly shouldnt work ... i didn't test that)

@affan00 can you see if this is a dashboard issue (I think it is) or a media issue and assign it correctly.

**Comment by affan00** [comment]
It's done and deployed.
