### ISSUE TITLE
Currently too many cameras are defaulting to UTC that should be Dublin or elsewhere

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1476]
1. Fix all our irish customers to be in Dublin. In your shoes, I'd do this with a GEOIP lookup.
2. Make a suggestion for a UX / Defaults improvement so that we help the user to get this right, more often.

**Comment by marcoherbst** [comment]
Discuss this with @Zulqarnain-Mustafa  , we talked about a related interface improvement on mobile. This will be a nice improvement.

**Comment by affan00** [comment]
Ok Marco.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by affan00** [comment]
Changed the timezone of the cameras to Dublin/Europe whose owner country is Ireland. Soon default timezone will be changed from Utc/Etc to Dublin/Europe from media.
