### ISSUE TITLE
[Airbrake] [Production] Missing template widgets/live_view_private_widget, application/live_view_private_widget with {:locale=>[:en], :formats=>["application/x-rtsp-tunnelled"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searche...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1478]
**Airbrake error:** [#9886](https://evercam.airbrake.io/projects/98599/groups/1782381693002479886)
**Airbrake project:** Evercam Dashboard

**Error type:** `ActionView::MissingTemplate`
**Error message:** `Missing template widgets/live_view_private_widget, application/live_view_private_widget with {:locale=>[:en], :formats=>["application/x-rtsp-tunnelled"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:   * "/app/app/views"   * "/app/vendor/bundle/ruby/2.3.0/gems/devise-4.2.0/app/views"`
**Where:** `widgets#live_view_private_widget`
**Occurred at:** Sep 25, 2016 05:14:29 UTC
**First seen at:** Sep 25, 2016 05:14:15 UTC
**Occurrences:** 3 (0 since last deploy on `<no information>`)

**URL:** [https://dash.evercam.io/live.view.private.widget?camera=wwcam&refresh=1&api_id=&api_key=&rtmp=rtmp://media.evercam.io:1935/live/DbTeafvsax-tXHK-U2grKK4ZnxSLn5WdGJpwmKC4o9aTevSvQUXkUzuy_pmw4aKqgk4fJ-LYMKwrjGgTy3IZJHnXmlrzKjV60hAVLyTwh3RMGk4PzmQpy_HdEPv7huyy?camera_id=wwcam&hls=rtsp://media.evercam.io:4000/live/DbTeafvsax-tXHK-U2grKK4ZnxSLn5WdGJpwmKC4o9aTevSvQUXkUzuy_pmw4aKqgk4fJ-LYMKwrjGgTy3IZJHnXmlrzKjV60hAVLyTwh3RMGk4PzmQpy_HdEPv7huyy/index.m3u8?camera_id=wwcam](https://dash.evercam.io/live.view.private.widget?camera=wwcam&refresh=1&api_id=&api_key=&rtmp=rtmp://media.evercam.io:1935/live/DbTeafvsax-tXHK-U2grKK4ZnxSLn5WdGJpwmKC4o9aTevSvQUXkUzuy_pmw4aKqgk4fJ-LYMKwrjGgTy3IZJHnXmlrzKjV60hAVLyTwh3RMGk4PzmQpy_HdEPv7huyy?camera_id=wwcam&hls=rtsp://media.evercam.io:4000/live/DbTeafvsax-tXHK-U2grKK4ZnxSLn5WdGJpwmKC4o9aTevSvQUXkUzuy_pmw4aKqgk4fJ-LYMKwrjGgTy3IZJHnXmlrzKjV60hAVLyTwh3RMGk4PzmQpy_HdEPv7huyy/index.m3u8?camera_id=wwcam)
**File:** `[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/path_set.rb`

**Backtrace:**

```
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/path_set.rb:46:in find
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/lookup_context.rb:121:in find
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:18:in find_template
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:40:in determine_template
```

**Comment by muneeb2542** [comment]
This is the same as #1421. So I'm changing the milestone to long finger

**Comment by muneeb2542** [comment]
Duplicate #1421
