### ISSUE TITLE
Dashboard not updating after public camera is shared with user

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1500]
I clicked on a link to a public camera, https://dash.evercam.io/v1/cameras/linkebeek/  it opened in my dashboard.

I clicked "Add to my account"

Nothing happened.

I clicked again and got an ill-formed error ( this is bugfix 1 )

Still the screen did not update, it should have updated to show the option to "remove camera from my account"

When I refresh the whole page, then all's ok.

**Comment by marcoherbst** [comment]
Related to: https://github.com/evercam/evercam-dashboard/issues/1349 ?

**Comment by affan00** [comment]
Had a discussion with Mr Azhar, both issues are similar, It's tricky so I am putting #1349 to future milestone and closing this one.
