### ISSUE TITLE
Archive/Create clip changes phase 2.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1506]
- [x] Duration 60 min.
- [x] Inline validation for duration
- [x] Refresh status auto
- [x] IF there are not recordings, then the button is deactivate
- [x] Add some space before "There are no clips"

**Comment by marcoherbst** [comment]
@affan00 all ticked, this is for closing?

**Comment by affan00** [comment]
@marcoherbst Yes, but still it is not deployed because right now, just waiting to increase duration from 30 to 60min from the media side.

**Comment by affan00** [comment]
It's live now so i am closing this.
