### ISSUE TITLE
Fix clone camera errors & Improve 'Add a camera' page layout.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1509]
As per email to Azhar,

- [ ] Cloning camera generated "error creating user account" error.  (weird?) then on retry, it worked.
- [ ] Geo settings were not cloned.

**Comment by marcoherbst** [comment]
- [ ] Evercam-ID ... auto-suggest and include an "available" green flag (like port open).
- [ ] Test snapshot > use this empty space and what's with the wierd little 4px box floating there?
- [ ] Copy From ... not clear what this means to a user ... it needs explaining. I think it's a tickbox or a button which then shows the option of choosing a camera .... this will not be used often, so it needs to be more subtle.
- [ ] Remove all LOCAL (under Advanced) and integrate RTSP port into the main form.
- [ ] Take lessons from our homepage where we show the vendor models as we load them.

**Comment by affan00** [comment]
It's done and deployed.
