### ISSUE TITLE
User activities log interface

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-dashboard#1522]
Create an interface to utilize the newly created endpoint for user activities logs.

`/v1/users/username/activities`

keep it same with evercam-media and do it as `dash.evercam.io/v1/users/username/activties`

Includes  Login Logout date and client info (think Intercom)

**Comment by marcoherbst** [comment]
@affan00 ,  @ijunaid8088 would prefer to push this out to a more distant milestone , so that's where it's going.

**Comment by marcoherbst** [comment]
@azharmalik3 sounds like this will be closed tomorrow. If not, then maybe create a new more detailed issue for v2 and close this anyway.

**Comment by azharmalik3** [comment]
Completed.
