### ISSUE TITLE
Testing the share with new user signup process ....

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1532]
Overview:
We are highly suspicious about this process and where it might be not working properly and confusing customers. Many customers are complaining that it doesn't work properly "email already in use" etc. errors when we know that this is not the case. I would like 2 people to conduct a thorough test with as many variations as possible to find where it is going wrong.

Consider for all cases below about active sessions / incognito windows ... try to break the system, where does it break? what can we do to fix it and make it more robust? 

Share with new user by email
= bad email address?
= email already used on this camera (but account doesn't exist)
= email already used on another camera (but account doesn't exist)
= email already used on an account (account exists)

Share with new user by username
 ... camera is already shared?
 ... camera not shared

**Comment by affan00** [comment]
It's done, Created new issue for bugs.
