### ISSUE TITLE
[Airbrake] [Production] key not found: "external"

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1535]
**Airbrake error:** [#1129](https://evercam.airbrake.io/projects/98599/groups/1808545261099841129)
**Airbrake project:** Evercam Dashboard

**Error type:** `KeyError`
**Error message:** `` key not found: "external" ``
**Where:** `cameras#single`
**Occurred at:** Oct 31, 2016 07:37:16 UTC
**First seen at:** Oct 31, 2016 07:37:16 UTC
**Occurrences:** 0 (0 since last deploy on Oct 07, 2016 06:03:05 UTC)

**URL:** [https://dash.evercam.io/v1/cameras/evercam-remembrance-camera](https://dash.evercam.io/v1/cameras/evercam-remembrance-camera)
**File:** `/app/config/initializers/overrides.rb`

**Backtrace:**
```
/app/config/initializers/overrides.rb:5:in fetch
/app/config/initializers/overrides.rb:5:in deep_fetch
/app/app/views/cameras/single/info/_settings_modal.html.erb:62:in _app_views_cameras_single_info__settings_modal_html_erb___726983453611219036_70029728112920
[GEM_ROOT]/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in block in render
```

**Comment by muneeb2542** [comment]
Fixed now
