### ISSUE TITLE
[Airbrake] [Production] Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1540]
**Airbrake error:** [#8810](https://evercam.airbrake.io/projects/98599/groups/1770183785343778810)
**Airbrake project:** Evercam Dashboard

**Error type:** `AbstractController::DoubleRenderError`
**Error message:** `` Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return". ``
**Where:** `widgets#snapshot_navigator_widget`
**Occurred at:** Nov 01, 2016 07:21:18 UTC
**First seen at:** Sep 08, 2016 09:19:11 UTC
**Occurrences:** 3 (0 since last deploy on Oct 07, 2016 06:03:05 UTC)

**URL:** [https://dash.evercam.io/snapshot.navigator.widget?camera=evercam-remembrance-camera&date_time=](https://dash.evercam.io/snapshot.navigator.widget?camera=evercam-remembrance-camera&date_time=)
**File:** `[GEM_ROOT]/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:15:in render
[GEM_ROOT]/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in block (2 levels) in render
[GEM_ROOT]/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in block in ms
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in realtime
```

**Comment by muneeb2542** [comment]
Duplicate #1553
