### ISSUE TITLE
Bad email verification on camera share request.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1541]
Tried with (affan.qureshi11@gmail,com, affan.qureshi11@@gmail.com, affan.qureshi11@@gmail.,com, affan.qureshi11@@gmail.,,,@com),
It sends the request successfully on bad email address.

Also, 

- [x] when share request sends at first the resend option have the icon instead of "resend" text. fix this
- [x] Use better regex here which is being used everywhere in the project for email validation.

**Comment by marcoherbst** [comment]
seems to me the essential thing here is to settle on a regex that is used client & server side and then not to discuss this anymore. 

no regex is perfect, but it seems to me that we spend a lot of time going around in circles on this. @affan00 , improve this issue by reference to regex being used elsewhere.

**Comment by affan00** [comment]
Use same regex as used in snapmail for email verification. regex: 
```
([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})
```
