### ISSUE TITLE
Check user is already signed up or not on resend request and send email accordingly.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1543]
follow these steps to find out:
step:1- Send a camera share request to the new user.      it will send the signup email to the receiver.
Step:2- Delete that request.
step:3- Again send a request to that receiver.         It will again send  signup email to the receiver.
step:4- Now new user signup with the first signup email. (email via deleted request)
step:5- User sign up but a camera is not available in his account. 
step:6- Sender camera share request is in pending status, Now sender press the resend email button. It will send again resend email for signup.
Step:7- If receiver tried to connect with the camera with that resend email the camera doesn't add.

Note: In order to share camera with the user the sender needs to again delete the sending request and create the new request again,

**Comment by marcoherbst** [comment]
I haven't totally followed the logic in the steps above, but want to clarify, this MUST be true:

When a user signs up (as a result of ANY mechanism) ANY valid outstanding pending shares are converted into active shares.

If that sentence is true, maybe the 7 steps above are not required ?

**Comment by affan00** [comment]
tested this again, It's fixed so closing this now.
