### ISSUE TITLE
Loading animation on calendar for /recordings

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1548]
Recordings calendar often takes a second or 2 to populate.

It might be nice to have a loading animation just so this is more obvious to users.

**Comment by marcoherbst** [comment]
Currently it takes a few microseconds for the numbers (even the non-blue numbers) to appear on the calendar. This might be a nice animation sequence ... show no numbers and let them appear only when there is data.  ( Just a thought , a regular animation is also perfectly ok ).

**Comment by marcoherbst** [comment]
@affan00  the more I think about it , the more I think we should not use an animation, and should instead better implement the gradual appearance of the numbers. Before tackling this, ask @ijunaid8088  his opinion and let him show you his relevant efforts in this field.

**Comment by affan00** [comment]
After consulting with @ijunaid8088 set the loading animation. It's done and live now.
