### ISSUE TITLE
[Airbrake] [Production] Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1553]
**Airbrake error:** [#9037](https://evercam.airbrake.io/projects/98599/groups/1814541128239839037)
**Airbrake project:** Evercam Dashboard

**Error type:** `AbstractController::DoubleRenderError`
**Error message:** `` Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return". ``
**Where:** `pages#live`
**Occurred at:** Nov 08, 2016 14:09:18 UTC
**First seen at:** Nov 08, 2016 14:09:18 UTC
**Occurrences:** 0 (0 since last deploy on Oct 07, 2016 06:03:05 UTC)

**URL:** [https://dash.evercam.io/live/zipyard-navan-foh](https://dash.evercam.io/live/zipyard-navan-foh)
**File:** `[GEM_ROOT]/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:15:in render
[GEM_ROOT]/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:44:in block (2 levels) in render
[GEM_ROOT]/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in block in ms
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in realtime
...
Caused by AbstractController::DoubleRenderError: Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
```

**Comment by muneeb2542** [comment]
Resolved now
