### ISSUE TITLE
Logs tab checkboxes & date sorting  not working .

### ISSUE THREAD

**Issue by ijunaid8088** [evercam/evercam-dashboard#1563]
![image](https://cloud.githubusercontent.com/assets/13561999/20235178/220f2bc4-a8ad-11e6-82dc-0e202f0b1710.png)
The above part of the tab is not working right.. as Now we have many other events being logged as well. One of them is `Cloud Recording` update/create. Now even if we put `All` as checked..then only those events come in logs which have been checked only. NOT Newly added ones as CR settings update/delete.

Date Sorting is not working.

**Comment by affan00** [comment]
It's done and deployed.
