### ISSUE TITLE
Snapmail Interface improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1572]
- [x] Responsivity isn't great, esp. with 1 or 2 snapmails only.
- [x] Add a title "Snapmail - Scheduled Emails"
- [x] More obvious how to add.
- [x] More obvious how to edit.
- [x] Alignment of Save / Cancel
- [x] Rslider for snapmail cameras thumbnail doesn't work without page reloading. fix this
- [x] Snapmail dialog box heading ('New snapmail' and 'edit snapmail') doesn't work properly. fix this
- [x] Fix the visibility of the text "you have not created any snapmail"

**Comment by affan00** [comment]
It's fixed and deployed.
