### ISSUE TITLE
7 Day Online Offline report (like Construction Cameras Report).

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1590]
This will be in /Settings/Online-Offline   

Using https://github.com/flrs/visavail plot the 7 day online / offline status of all cams in user's account.

Later,
- [ ] There will be an option to "Send this report each day at XX:XX" to email [       ]"

**Comment by marcoherbst** [comment]
![online-offline](https://cloud.githubusercontent.com/assets/5648894/21354634/ca6cdca2-c6c2-11e6-82fe-1846204c5282.png)

**Comment by marcoherbst** [comment]
https://github.com/flrs/visavail

**Comment by ijunaid8088** [comment]
Today I deployed the Online Offline Report, Everything was working fine locally but in the production, DB is giving timeout errors and Dashboard started giving application errors. Why DB gave timeout, am not sure about this issue, BUT with snapshotDBUrl in local system, report for my cameras worked well but on Vinnie's Cameras query didn't get the results, there few reasons, When we load any template in dashboard, we formally do a query for all user cameras including shared ones, and the JSON coming from evercam server for this query, Don't include any Integer ID of a camera, its only camera_exid, which is TEXT, I tried in this way that gets All camera's exids and then from these Exids, again get all cameras through which I got integer ID, which was too slow, and Between Query with all camera_exid only work when total cameras are less, 

As in start I suggested we should add an endpoint for this, 

We have worked on a similar task where there is specific JSON was needed, This task has the same case, getting all records and then formatting them, take so much time that its obvious.

I see only 2 options to get this working efficiently and useful,
1: Endpoint
2: show only 3 or 5 camera's reports per page, and send request for logs on next page click

**Comment by ijunaid8088** [comment]
am closing this as version 1 deployed and adding a new one with the points mentioned in emails

**Comment by marcoherbst** [comment]
You can leave out the requirement for "Send by Email". We might implement that in a v2.0. 
Do remember to add this to the dashboard so it can be found.

**Comment by marcoherbst** [comment]
@ijunaid8088 , I'd say this can be closed now, eh? There is another issue for adding timescope and we'll leave out the scheduled email. If so, then close it pls.

**Comment by ijunaid8088** [comment]
Yes, I also added the fa icon thing in the report, as well as @flrs, has added support for fa icons and HTML in the report. (Its in PR)..

Other than that, It should be closed.

About scheduled email, I am looking for saving the whole SVG's out put to a PNG or Jpeg and then send it..
