### ISSUE TITLE
When i specify vendor / model, dont let me edit snap or rtsp URLS

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1596]
See how it's done on Android (or ask Nain)

I actually thought we did this before, maybe not.

**Comment by affan00** [comment]
It's already implemented.

**Comment by marcoherbst** [comment]
ok, but badly. It needs to really hide the 2 fields much more obviously.

Also "RTSP" should, I suppose be "RTSP URL" ... 

put a bit more love into this. then close.

**Comment by affan00** [comment]
It's done and deployed. Added RTSP url option in 'add ip camera' page and make the snapshot and rtsp non-editable URL's more obvious.
