### ISSUE TITLE
Details Page improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1610]
Read Only:

![image](https://cloud.githubusercontent.com/assets/5648894/21310948/ad5a0658-c5dc-11e6-8157-dd627ceb5810.png)

The not available URLs dont need to be shown.
The jpeg / Thumbnail URL is missing.

**Comment by marcoherbst** [comment]
Discussed. 
Correct, the URL to camera is not available to RO users.
But, the Evercam Snapshot URL IS available, that's the one I'm talking about.

**Comment by affan00** [comment]
It's done
