### ISSUE TITLE
Design of Snapmail page when there are no snapmails created.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1627]
Some nice explanatory text to encourage people to use it.

**Comment by marcoherbst** [comment]
Use image from this area:
https://evercam.io/construction-timelapse/features/

Use text:

Snapmail is a scheduled email that contains a snapshot from your camera. Include as many emails and cameras as you like.

This clever feature sends you up-to-date, high-resolution images direct to your inbox

Send images the day before a site meeting or send all project stakeholders a daily/weekly update.  

Now everyone is updated, and you haven’t left your desk.

---------

Consider responsiveness etc.

**Comment by marcoherbst** [comment]
@affan00  I've added some spec to this, it's ready to go and, I hope, relatively easy.

**Comment by affan00** [comment]
It's done.
