### ISSUE TITLE
Make more Intercom events using intercom API

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#1638]

**Comment by azharmalik3** [comment]
@marcoherbst I think about intercom events and all possible events which we can add in our system. Here are some events:

* Create camera
* Failed create camera
* Update camera
* Create camera share / share-request
* Delete share / share-request
* Delete camera
* Create archive
* Delete archive

I think these events should be in `evercam-server` instead of the dashboard.

**Comment by marcoherbst** [comment]
Phase 1:  Do as many of these as you can, please.

- [ ] Viewed Camera (integer)  (Has used live view)
- [ ] Viewed Recordings (integer) (Has used recordings)
- [ ] Has-Shared (boolean) (Has shared a camera with someone)
- [ ] Has-Snapmail - (boolean) (is the recipient of at least one snapmail)

**Comment by marcoherbst** [comment]
Completed. Thanks.
