### ISSUE TITLE
Add menu for status report under status report

### ISSUE THREAD

**Issue by ijunaid8088** [evercam/evercam-dashboard#1659]
I have added an optional parameter as `history_days` for Status Report.

Please add 5 links under that tab as we have for settings tab.

1 Day, 3 Day, 7 Day, 30 Day and 90 Day..

And for adding query params to route your will use this

`<%= link_to "90 Day", status_path(:history_days => 90) %>`

**Comment by affan00** [comment]
It's done so I am closing this issue.
