### ISSUE TITLE
Snapmail unsubscribe improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1660]
When unsubscribing, the text isn't great and it's not clear whether the whole snapmail is being deleted or just my email is being removed from it.

![image](https://cloud.githubusercontent.com/assets/5648894/22327775/c9c75db2-e3b0-11e6-95f0-f3f9ed78e45b.png)

**Comment by marcoherbst** [comment]
I think an additional sentence would do the trick:

"If other email addresses are still subscribed to this Snapmail, they will continue to receive emails."

@affan00  you can do this & close it today.

**Comment by affan00** [comment]
It's done.
