### ISSUE TITLE
Owner Transfer process is a bit wrong

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1662]
Currently, I do an owner transfer and I get a warning "You may loose access". I click ok, ownership is transferred and I am sent back to the /cameras dashboard ... all ok, 

BUT

I still have full-rights access to the camera. So, the whole process was a bit misleading.

The Fix: (Suggested, you might have a better idea):
Don't show the warning, instead explain that you will still have full-rights.
Don't send customer back to /cameras , keep them on the /shares page.

I'm assigning @azharmalik3 as I think he knows this flow best, but please feel free to talk it through with @affan00  and reassign.

**Comment by azharmalik3** [comment]
Message changed on transfer popup and also stopped page reloading.
