### ISSUE TITLE
CloudRecording module is not showing calendar events.

### ISSUE THREAD

**Issue by ijunaid8088** [evercam/evercam-dashboard#1700]
For all those cameras which are on `On Schedule` cloud recording, when you click on edit, the pop up doesn't show any calendar events for schedule. 
Also, It sometimes prompted to give a title to calendar events. That must be removed.

**Comment by affan00** [comment]
This issue is due to the bug in the moment gem latest version that 'getParsingFlags' is returning undefined 'parsedDatePart' property, resolved the issue by downgrading the moment gem version to 2.12.0.
