### ISSUE TITLE
Add lens zoom to /recordings 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1710]
We had something like this on Camba

I think one could have a magnifying icon beside the save icon , clicking this gives a circle of magnification (probably only to true resolution) and clicking again (anywhere) disables it. You might have a better idea than this.

I'm thinking of "Lens zoom" or similar:
http://www.elevateweb.co.uk/image-zoom/examples

**Comment by marcoherbst** [comment]
... Or, consider having the zoom controls below the calendar on /recordings.

**Comment by marcoherbst** [comment]
Thinking about this again, take some time to do a demo on a touchscreen computer. This is, I think, much nicer than a lens. I think the best way will be more like Google Maps zoom. @affan00  , ask @marcoherbst when the time comes.

**Comment by affan00** [comment]
It's done.
