### ISSUE TITLE
Improve the expired invite error

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1711]
The error for a used invitation is 

![image](https://cloud.githubusercontent.com/assets/5648894/23915715/c83eaca6-08e1-11e7-884b-15a4edae4ca2.png)

I think it needs to be clearer.

I think it needs to be the main event on the screen: This signup link has been used already.

You should either login to your existing account or create a new account.

Something along those lines.

**Comment by marcoherbst** [comment]
Change the text to:

**This signup link has already been used by xxx@xxx.com

You should either login to your existing account or create a new account.**

**Comment by affan00** [comment]
It's done.
