### ISSUE TITLE
Logs page layout improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1729]
![untitled-1](https://cloud.githubusercontent.com/assets/5648894/24604553/1a0e9b88-185d-11e7-906e-41f4a06fc21b.gif)

Something like this, but nicer.

**Comment by marcoherbst** [comment]
Also, careful of font size ( From and To are too small )
Use all the filter toggles, not just the ones in the screenshot.
Default to showing last 50 events. 
Show Report button should be beside Text Search.

**Comment by ijunaid8989** [comment]
This part has been done. I am referencing this to another issue where I am working on the other half.
