### ISSUE TITLE
"Username has already been taken"

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1734]
Prompt the user with a nicer alternative.

Before doing this, ask @azharmalik3 if he thinks the available options should come from the API response. 

Also, discuss once with @azharmalik3 and  @marcoherbst about the possibility of replacing usernames with emails.

**Comment by marcoherbst** [comment]
This is now ready:
https://github.com/evercam/evercam-server/issues/735

**Comment by affan00** [comment]
It's done.
