### ISSUE TITLE
NoTranslate on Dashboard pages

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1735]
Try:

```
<meta charset="UTF-8">
<meta name="google" content="notranslate">
<meta http-equiv="Content-Language" content="en">
```

As per:
http://stackoverflow.com/questions/2980520/how-to-specify-your-webpages-language-so-google-chrome-doesnt-offer-to-transla

To avoid this:
![image](https://cloud.githubusercontent.com/assets/5648894/24708491/e06d4a6a-1a0e-11e7-855c-c85e7c303fc6.png)

**Comment by affan00** [comment]
It's done.
