### ISSUE TITLE
Simplify /cameras/new by removing local info

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1737]
- [x] Remove Local IP, http and rtsp.
- [x] Remove option "Additional Settings"
- [x] Move "External RTSP port" to vertically below HTTP Port . Add label (optional)
- [x] Move RTSP URL to align vertically on the right of RTSP URL (below HTTP URL)
- [x] The text for "Snapshot URL" is different to how all other labels are done. Fix that.
- [x] Copy settings from ... This whole text label should be an active clickable object

![image](https://cloud.githubusercontent.com/assets/5648894/24714757/5380734e-1a21-11e7-9b9c-44f8eeb4c8b5.png)

- [x] Also, the red error "Select Default if you're unsure" seems to be active all the time .... instead have this as a mouseover futher info "?" 

If you see a nice way to add the Vendor Model images, then do that. Not important.

**Comment by affan00** [comment]
It's done.
