### ISSUE TITLE
Log improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1749]
Combine related items:
[ ] Online / Offline
[ ] Cloud Recording Settings
[ ] Sharing Settings
[ ] Archive Settings
[ ] Camera Settings

Is Captured used? If not, take it away.
Find out the difference between accessed and viewed.

Align them better (?) ask if confused.

**Comment by ijunaid8989** [comment]
https://github.com/evercam/evercam-dashboard/issues/1729

**Comment by ijunaid8989** [comment]
its done.
