### ISSUE TITLE
Port Open test seems to be unreliable. 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1761]
I strongly suspect this is a front-end issue, not an issue with the port test API.

**Comment by marcoherbst** [comment]
@affan00 can you handle this? If not, pass it to someone else.

**Comment by affan00** [comment]
Sometimes the port check endpoint returns the wrong response.
I tested it many times from the front-end point of view but it seems to be server side issue.

The camera is online but on details, port status is closed.

**Comment by marcoherbst** [comment]
Did you re-create the issue?
Before this issue is closed I'd like to see a more detailed response with an actual example.

**Comment by affan00** [comment]
Yes, I created a new issue in evercam-server and I will update snapshot of actual example as soon as I am able to reproduce the error.

**Comment by affan00** [comment]
Made port status test more reliable from the client side. So I am closing this.
