### ISSUE TITLE
This email is already in use: spot this before pressing submit

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1773]
like these guys:

![image](https://cloud.githubusercontent.com/assets/5648894/25556523/017562a2-2cf6-11e7-8721-03cecbf827ed.png)

**Comment by marcoherbst** [comment]
Ditto username.

**Comment by affan00** [comment]
Need new endpoints for username and email address validation, https://github.com/evercam/evercam-server/issues/735

**Comment by affan00** [comment]
It's already done. So, I am closing this.
