### ISSUE TITLE
Sign-up doesn't work on mobile devices.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1775]
On creating new account 'https://dash.evercam.io/v1/users/signup' using mobile devices when clicked on 'create new account' button nothing happens.

**Comment by marcoherbst** [comment]
@affan00 this issue needs more description please

**Comment by affan00** [comment]
This issue is related to bad username validation https://github.com/evercam/evercam-dashboard/issues/1776 so I am closing this issue.
