### ISSUE TITLE
Better failing when Seaweed timeouts POST

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1782]
Today Dashboard crashed due to Seaweed timeout errors.

1) Would be better if dashboard didn't crash
2) It is essential that admins are notified of the problem.

**Comment by marcoherbst** [comment]
@azharmalik3 is this completed? If not, could you make some notes about what could be done here, and by whom.

**Comment by azharmalik3** [comment]
Made following changes into dashboard and media:

- Made changes in `evercam-media` to add seaweed fail request logs into sumo instead of raising an exception.
- Also, added server down message page into the dashboard and send an email notification to admins.
