### ISSUE TITLE
When I click on /maps, zoom to a useful resolution… 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1785]
There are various threads about this on SO.

http://stackoverflow.com/questions/11454229/how-to-set-zoom-level-in-google-map

**Comment by marcoherbst** [comment]
@ijunaid8989 IF you thought this is something you have a good chance of solving quickly, since you've done plenty of work with maps, you're welcome to take this task, if you're ready  for it.

**Comment by marcoherbst** [comment]
@affan00 , to clarify:

Currently when I view a map, it defaults to zoom out (max) . 

It should be possible to default to a more sensible zoom level & region.

For example, if all of the cameras to be displayed are in Berlin, then we should zoom only to Berlin.

There are several discussions online as to how to do this. Keep it in June Milestone, low priority.

**Comment by affan00** [comment]
Set zoom of a map to cover all visible markers. It's done.
