### ISSUE TITLE
Dashboard left nav, minor changes.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1786]
- [x] Move Maps & Status Report to the main menu.
- [x] Remove Cameras Table (rename it /table and hide it from navigation, it’s a hidden feature)
- [x] Remove “Public Cameras” link from Dashboard
- [x] Move the “Hide offline cameras [ ]” from the left nav to the Account Settings Page. Make it a toggle underneath the API ID & Key area.

**Comment by affan00** [comment]
It's done.
