### ISSUE TITLE
Logs page design improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1822]
@affan00 , I suggest having a voice call before you work on this.

- [x] Reduce the height of the horizontal status bar. 
- [x]  Default to 30 days, not 2 days so we see more valuable info. Or default to 50 items? position.
- [x] The icons for + , - are a bit aggressive. Simpler, colourless font based ones would be nicer. [+] [-] more like MS file explorer.
- [x] Improve 'cloud recording logs' table layout.

**Comment by affan00** [comment]
It's done.

**Comment by marcoherbst** [comment]
hmmm.... Ping me to discuss. For some of those items I don't see changes.

**Comment by affan00** [comment]
It's done. So, I am closing this issue.
