### ISSUE TITLE
Logs layout improvement v2

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1833]

**Comment by marcoherbst** [comment]
<img width="788" alt="logs page 1" src="https://user-images.githubusercontent.com/5648894/28028542-c54ba660-6594-11e7-8999-1f6219fa30aa.png">


<img width="788" alt="logs page 2" src="https://user-images.githubusercontent.com/5648894/28028545-c7b95c6c-6594-11e7-8dab-3814d23b8129.png">


<img width="795" alt="logs page mobile" src="https://user-images.githubusercontent.com/5648894/28028552-ca4999f6-6594-11e7-9d53-e0edba3c39ac.png">


Images courtesy of @annagillespie
