### ISSUE TITLE
/Projects section on the homepage.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1846]
This is nicely done:

![image](https://user-images.githubusercontent.com/5648894/28247384-fd20f20c-6a26-11e7-96df-7c1d8ef38ac8.png)

**Comment by affan00** [comment]
It's done. Add Evercam project section below the features section.

![image](https://user-images.githubusercontent.com/14149453/29057372-62fbb82e-7c23-11e7-8038-d3de07fadf86.png)
