### ISSUE TITLE
Share with multiple emails (Client Side Work)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1848]
This needs cleaning up ... it's an important part of the system and should be beautiful & bullet proof. Can be an @affan00 task (maybe with some help from @ijunaid8989 )

**Comment by affan00** [comment]
Added following functionalities;

- Now emails tag separates when user enter comma or semicolon or blank space.
- Remove auto select email.
- If you copy paste more than one emails it automatically separates tags on the basis of a semicolon comma or blank space.
- As we are allowed to use both username and email for sharing purpose so there is not proper validation for an email address.

**Comment by affan00** [comment]
It's done.
