### ISSUE TITLE
Local Recordings "Jump To" redesign

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1860]
![jumpto](https://user-images.githubusercontent.com/5648894/29119563-8bd3d098-7cfe-11e7-9ad9-0e18f21476af.gif)

Ok, @azharmalik3 ?

Feel free to use your own design for the data input, but i had in mind something like http://keith-wood.name/timeEntry.html with 24hr clock and seconds enabled. I don't see a need for pickers.

**Comment by marcoherbst** [comment]
@azharmalik3 you are welcome to give this task to Affan if it helps you. BUT ... I have put it in your name as it should tie in nicely with the whole rest of the page. Ideally, as the video plays, the time might update. These things might be pretty tricky. You can decide.

**Comment by azharmalik3** [comment]
Done.
