### ISSUE TITLE
Preset(s) for scheduled recording

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1870]
To make it easy to choose: "Mon to Fri, 7-19 & Sat 7-14" for cloud recording schedule.

Needs some discussion with @marcoherbst

**Comment by affan00** [comment]
It's done. Added presets for the scheduled recording.
1) Mon to Friday 24hrs.
2) Mon to Fri 07:00-19:00 & Sat 07:00-14:00
3) Office closed timings Mon to Fri 18:00-08:00 & sat & sun
4) Office timings Mon to Fri 07:00-19:00
