### ISSUE TITLE
Downloading Jpeg on IE11 is not working

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-dashboard#1877]
Using IE11, jpeg view, when I download snapshot there is an error.
Also, on video view there is no download snapshot error (ask @azharmalik3)

**Comment by affan00** [comment]
This issue occurs on both IE & Microsoft Edge browser on "Video view and on save recording snapshot".

We were using "SaveImage.save" function for saving the image and it's not working on IE and Microsoft Edge. So I fixed this issue by using ''download.js" plugin for download the image. http://danml.com/download.html
