### ISSUE TITLE
<BR> format?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1881]
Im not even sure if this is a real thing, but IE11 thinks it is:

![image](https://user-images.githubusercontent.com/5648894/29620197-2f866914-8815-11e7-8322-cc03cba1a73c.png)

In general, go through the site with console open and look for errors.

**Comment by affan00** [comment]
It's done.
Fixed "br" tag warnings.
Fixed mixed content errors on the map page.
