### ISSUE TITLE
Update sequel gem to its latest version 5  gives an error on status report.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#1900]
**Console Errors**

- Uncaught ReferenceError: showError is not defined.
- Uncaught TypeError: Cannot read property 'length' of undefined.

**Comment by marcoherbst** [comment]
@ijunaid8989 @affan00 is this not done?

**Comment by ijunaid8989** [comment]
@marcoherbst update done and the errors are removed as well but tests are failing at the moment. that why this isn't closed yet.

**Comment by ijunaid8989** [comment]
its done.
