### ISSUE TITLE
Use animated logo for loading ....

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1906]
![ec-animated-logo1 1](https://user-images.githubusercontent.com/5648894/30379651-1b735fa6-988f-11e7-9c60-89130a352733.gif)

**Comment by affan00** [comment]
Changed Evercam logo gif on Snapmail, Single Snapmail & Status report tab. It's done.

**Comment by affan00** [comment]
Pay attention to file size
Pay attention to using a file that has higher resolution than needed - resample!
Try not to use amateur free websites
Try to use more professional tools like GIMP or Adobe

**Comment by affan00** [comment]
It's done.
Used GIMP software for changing the gif mode to an infinite loop.
Size of new Evercam animated gif after resample is 7kb.
Used in status report & local recordings.
