### ISSUE TITLE
Progressive Web App Audit

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1909]
Chrome > Dev Tools > Audits

https://developers.google.com/web/progressive-web-apps/checklist

**Comment by affan00** [comment]
Result for https://dash.evercam.io/v1/cameras
This includes:
Site is served over https -- yes
Pages are responsive on tablets & mobile devices -- yes
Site works cross-browser -- yes
Does not register a service worker --  no
First load fast even on 3G -- yes
Each page has a URL. -- yes
Respond with a 200 when offline -- no
User will not be prompted to Install the Web App -- no
Address bar does not match brand colors -- no
Contains some content when JavaScript is not available . -- yes
Has a <meta name="viewport"> tag with width or initial-scale. -- yes
Content is sized correctly for the viewport. -- yes
The page does not contain a heading, skip link, or landmark region.. -- no
Color Contrast Is Satisfactory. -- yes
Elements Describe Contents Well. -- yes
Meta Tags Used Properly. -- yes
Elements Are Well Structured. -- yes
Background and foreground colors have a sufficient contrast ratio.. -- yes
Includes front-end JavaScript libraries with known security vulnerabilities: 2 vulnerabilities detected. -- no
