### ISSUE TITLE
Do the big WP migration, and setup EdgeCommander while we're at it.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1910]

**Comment by marcoherbst** [comment]
Step 1: Find our monthly cost for current WP installs.

Evercam
MalariaMuseum
Camba.tv
Future: Edge-Commander

Step 2: Herbst / Flavio recommend SiteGround. We'll see.

**Comment by affan00** [comment]
It's done, Migrated sites(Evercam, Malariamuseum & Camba.tv) from AWS to SiteGround, So I am closing this.
