### ISSUE TITLE
Go through each Gem, understand it, and look for opportunities to optimise

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1924]

**Comment by affan00** [comment]
List of removed gems:

- fog gem replaced with fog-aws.
- heroku-api -- Removed
- rails_12factor -- No need to be used in rails 5.
- rack-rewrite --  Removed
- typhoeus -- removed separate typhoeus gem, already used in evercam gem.
- vcr -- Removed

It's done. I am closing this now.
