### ISSUE TITLE
JG Updates

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1951]
- [x] From title, remove "Construction" so title is on one line.
- [x] Timelapse == Time-lapse everywhere
- [x] "Features" & Other headings all centralised.
- [x] Bottom 3 logos, move bridgedale to column 4 so they are all centralised.
- [x] "Projects Powered By...." make this 2 rows of projects and remove the "See more" hyperlink and keen the button.

**Comment by affan00** [comment]
It's done,
