### ISSUE TITLE
Show image size estimates in dashboard.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1970]
Image Size:
Total GB (est.)
Monthly GB (est.)

https://docs.google.com/drawings/d/10dvQiaJVLahqDB2ymre3R3cFGWJfzjrm-OZ7MxxLys4/edit

I think a subtle (i) info icon in bottom right corner to give us these details (popup).
http://fontawesome.io/icon/info-circle/

|   |                  |           |                      | 
|---|------------------|-----------|----------------------| 
| A | Snapshot size    | 300kb     |  < this is current jpeg                    | 
| B | Hours per day    | 24        | # hrs per week/7 | 
| C | Jpegs / Hour     | 3600      |                      | 
| D | Days Storage     | 7, 30 etc. |  or use create date if unlimited                    | 
|   |                  |           |                      | 
|   | *Estimates*        |           |                      | 
|   | Monthly GB (est.)|           | ABC x 30             | 
|   | Total GB (est) |           | ABCD              |

**Comment by affan00** [comment]
It's done, I am closing this now,
This information is available if camera recording is not "pause" and "off", This calculation is based on the image file size loaded on recording tab.
