### ISSUE TITLE
Add some of the simple API calls to the Developer Pages

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1973]
sample API calls:
GET Snapshot (Live)  ( https://api.evercam.io/v1/{camera-id}.....
GET Snapshot (Recorded)

It would be enough to have a simple 1 line generator with a select box to choose the camera and populate with ID & Key. For the recorded image, a date & time selector or text box would do.

There may be one or 2 more interesting API calls, but I think these are the 2 that I can think of right now.

Put it on a new tab "API" on https://dash.evercam.io/v1/users/construction/settings and move the API ID & Key from account settings to that page. 

(Then you will also want to relocate the "show hidden" to a better location on the tab it's currently on.

**Comment by affan00** [comment]
It's done and live now so I am closing this.
