### ISSUE TITLE
Dashboard layout responsiveness ....

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2024]
It's nearly ok, how it jumps from 3 cams to 2 to 1 as the space is reduced, but I think the 2 column layout needs to come sooner .... see this screen:

![image](https://user-images.githubusercontent.com/5648894/35142827-75e13018-fcf7-11e7-8556-274937037f58.png)

2 column would be more suitable, no? Needs some thought. I'm not 100% confident.

**Comment by affan00** [comment]
What I did is that:
Set two column layout if cameras count is less than 3 and if the screen resolution is less than 1400.
Set three column layout if cameras count is greater than 2 and if the screen resolution is greater than 1400.
So I am closing this now.
