### ISSUE TITLE
Archives small changes

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2129]
Using nelab-tavfi as an example:

- [x] URLs should have an Edit Action.
- [x] Click on Title or Created to sort by

**Comment by marcoherbst** [comment]
Related: https://github.com/evercam/evercam-server/issues/941

**Comment by azharmalik3** [comment]
@affan00 URL update functionality added in archives endpoint. 
Add `url` param in patch request.

**Comment by affan00** [comment]
It's deployed now, So I am closing this issue.
