### ISSUE TITLE
OGP MetaData for any page that could be shared publicly.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2148]
1.  Make a list of every page or object which could usefully make use of  http://ogp.me/  MetaData
2.  Add the relevant MetaData

e.g. 

```
<meta property='og:title' content='Title of the article"/>
<meta property='og:image' content='//media.example.com/ 1234567.jpg"/>
<meta property='og:description' content='Description that will show in the preview"/>
<meta property='og:url' content='//www.example.com/URL of the article" />
```

https://dash.evercam.io/v1/cameras/stephens-green/  would be an example, and I guess, also any public archives which could be linked to.

Marco

**Comment by affan00** [comment]
Added OGP metadata for public cameras. It's done. I am closing this now.
