### ISSUE TITLE
Archives: Try a layout more similar to Snapmail (boxes, 3 or 4 per row)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2164]
@affan00 , probably best to leave this for a while. @JaviCT is doing some relevant (and very good) work in this area. 

so, if you want to show us a quick mockup (pen paper or similar,) fine. but don't invest serious time and effort in a finished result.

**Comment by JaviCT** [comment]
- [ ] Add share and actions buttons (three dots?)

- [ ] Fix height on view and width on scroll panel 

- [ ] Title link on list view open the new design

**Comment by marcoherbst** [comment]
Duplicate Issue
