### ISSUE TITLE
explainer text for GIF and MP4

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2165]
Currently, the hover-text is "Download GIF" change it to:

"Download GIF (Good for emails)"

and

"Download MP4 (Good for everything else)"

There are 2 or 3 places where this is relevant.

**Comment by affan00** [comment]
I've added in archive tab download icon for compare archive, single archive download icon, share dialogue box download icon and compare dialogue download button. It's done, I am closing this now.
