### ISSUE TITLE
Use OG Data on All Archives where possible

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2215]
Use OG Data on All Archives where possible

![image](https://user-images.githubusercontent.com/5648894/43833207-ecfc0882-9b01-11e8-8f73-840995dce65d.png)

http://ogp.me/

Related: https://github.com/evercam/evercam-server/issues/867

**Comment by JaviCT** [comment]
The links to media.evercam.io should have: 

- Title
- Description
- Image
- Url
- Type

Metadata: http://ogp.me/
Metadata for twitter: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary.html

**Comment by azharmalik3** [comment]
Added missing metadata for all archives and now it covers for almost all type archives.
