### ISSUE TITLE
X-Ray idea

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2243]
Select a portion of the image and go back in time.
- [x] Easier to select (and adjust) edges.
- [x] Better Icon

**Comment by marcoherbst** [comment]
@affan00 

One small change - can you increase the area that allows user to drag and change the size of the x-ray box ... so it is easier to do this.

Then close this issue and pat yourself on the back. Well done.

**Comment by affan00** [comment]
It's done, I am closing this now.
