### ISSUE TITLE
Thank you page / newsletter ideas ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2274]
- [x] Fix vertical scroll on the thank you page
- [x] Fix the slug on thank you page
- [x] Experiment: When subscribed to newsletter, can that box be replaced by the thank you video? If not, then consider the message and improve it.
- [x] Design a block that can be inserted into bottom of blog posts and project pages.
- [x] Design an independent page /subscribe to sign up to newsletter (Erika can think of clever beautiful visuals for this) so that we have a CTA link for newsletters etc.

**Comment by affan00** [comment]
It's done, So I am closing this now.
