### ISSUE TITLE
Add Zoom to Archive Clip and live view VideoJS.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2306]
Azhar thinks this plugin exists.

If so, please add it.

e.g. /onewi-qroga/archives/siskon-uy9p 

M

**Comment by azharmalik3** [comment]
Try: https://github.com/xbgmsharp/videojs-rotatezoom

**Comment by marcoherbst** [comment]
@affan00 if this is not relatively easy, then put it into a long-finger milestone. It's only of interest if it is straightforward.
