### ISSUE TITLE
Find a way of getting alerts for broken functionality in dashboard.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#2315]
e.g Should be an alert for the broken/corrupted oldest camera image on the compare tab.

**Comment by marcoherbst** [comment]
e.g. https://github.com/evercam/evercam-dashboard/issues/2304

**Comment by marcoherbst** [comment]
In fact, I'll close that issue and paste the text here:

When a user signed up with a "_" in their email, the system didn't work.
There was no obvious error message or notification of failure.
Could we improve that, please.

**Comment by affan00** [comment]
I am closing this issue now, already send detailed info to Marco.
