### ISSUE TITLE
Move Non-Evercam WPs to Avada

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2327]
- [x] Litterbug.cam
- [x] Komp.ly
- [x] Komply.co.uk

**Comment by affan00** [comment]
It's done. I am closing this now.

- Used the 15px body font-size for all the three websites.
- Used the same Font family as we used in the Evercam public site for all the three websites.
- Used the blue colour theme for all the three websites.
- Used the 14px font size for the main menu for all the three websites.
- Removed the unused plugins e.g Gutenberg, post grid etc.
