### ISSUE TITLE
Back Button Bugs

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2384]
1. I am on Archives, then I go to Recordings, Edit Image and click on "Back" (Evercam) ... it takes me to the wrong place.

2. I am on Archives (Grid View) and I click into an Archive and then I select "Back" (Browser) ... and it should take me to a single archive, but it takes me to /cameras/

**Comment by affan00** [comment]
It's fixed now. I am closing this issue.
