### ISSUE TITLE
Some Interface Changes pre-Eid

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2465]
- [x] Hide the Status Report
- [x] Remove Snapmails from Tabs
- [x] Hide Add A Camera (?)

**Comment by marcoherbst** [comment]
Hide the report, it can still be there is someone knows the URL.

Same with add a camera, also please make a redirect to /add so that it's easy to remember

m

**Comment by affan00** [comment]
It's done, I am closing this now.
