### ISSUE TITLE
Restrictive ruby version on Gemfile

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-dashboard#596]
Having a ruby version mentioned in Gemfile like '2.2.0' is restrictive as the minor version on my system and also others system may not be the same as the one mentioned. Also the minor version have little to do with the actual working on the project. So I suggest to use the method described here to set the minimum ruby version required:

 http://stackoverflow.com/questions/28440712/how-can-i-specify-a-minimum-ruby-version-in-a-gemfile

**Comment by marcoherbst** [comment]
@shankardevy These are excellent comments and very helpful. Many thanks ... really useful input.

**Comment by muneeb2542** [comment]
Done
