### ISSUE TITLE
Live View JPEG Feed is stretched vertically

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#599]
As you can see on the screenshot, snapshot isn't shown in the original image ratio, instead it's stretched to fill the height available:

![image](https://cloud.githubusercontent.com/assets/1229422/8787405/267ac4aa-2f34-11e5-8575-7bbb30b170ae.png)

@azharmalik3

**Comment by marcoherbst** [comment]
I feel a slight sense of deja vu here.

The intended behaviour is to never distort the image aspect ratio and to
use the maximum available space. Always. Live & Reocrded and Widgets, jpegs
/ streams .... whatever.

If there's any uncertainty about the intended behaviour, then ask me. But
basically try to follow the rule above.

In the screenshot above that would have meant using the max width but not
max height.

Good stuff.

M

On 20 July 2015 at 22:09, Miloš Mošić <notifications@github.com> wrote:

> As you can see on the screenshot, snapshot isn't shown in the original
> image ratio, instead it's stretched to fill the height available:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1229422/8787405/267ac4aa-2f34-11e5-8575-7bbb30b170ae.png>
>
> @azharmalik3 <https://github.com/azharmalik3>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/599>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
Fixed.
