### ISSUE TITLE
Live View JPEG Widget is expanded out of bounds of the container

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#600]
![image](https://cloud.githubusercontent.com/assets/1229422/8787897/03d14174-2f37-11e5-974f-98fc47ebca11.png)

@azharmalik3

**Comment by azr5318** [comment]
Interestingly, if you doubleclick (full-screen) and then doubleclick again
... it then reverts to the proper size.

m

On 20 July 2015 at 22:30, Miloš Mošić <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/1229422/8787897/03d14174-2f37-11e5-974f-98fc47ebca11.png>
>
> @azharmalik3 <https://github.com/azharmalik3>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/600>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
