### ISSUE TITLE
Edit Camera Details interface issues ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#601]
I selected Hikvision vendor, but see no Model options.

I have 2 scrollbars on right hand side.

The Test Snapshot image is cropped ... probably best to let it "fit to height".

![screenshot-dash evercam io 2015-07-22 13-02-25](https://cloud.githubusercontent.com/assets/5648894/8824894/04e4a768-3072-11e5-9fdf-4c67055ce4c4.png)

**Comment by marcoherbst** [comment]
@azharmalik3  a reminder to look at this ASAP please.

**Comment by azharmalik3** [comment]
Fixed empty Model options, two scroll bars and croped image.
