### ISSUE TITLE
Registration error messages are not shown to the users 

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-dashboard#612]
To reproduce:
Use this link to create an account:
https://dashboard.evercam.io/v1/users/signup?key=b1202538270207ae45182f12302636254c5944b916594c96bc

Give an username that already exists, eg: 'shankardevy'  and submit it. You will not get registered but at the same time you will not see any error.

![screen shot 2015-07-27 at 7 12 24 pm](https://cloud.githubusercontent.com/assets/2011812/8923169/cd4c04ca-350a-11e5-9857-424e6a1683af.png)

Now, try to submit the form again with the same username 'shankardevy' and this time you will see the error message 'Username already exists'.
![screen shot 2015-07-27 at 7 12 39 pm](https://cloud.githubusercontent.com/assets/2011812/8923178/e09a9302-350a-11e5-9463-3a8fc881429e.png)

Now if you go back to original link https://dashboard.evercam.io/v1/users/signup?key=b1202538270207ae45182f12302636254c5944b916594c96bc
you will see the error message is still persisting before you submit the data

![screen shot 2015-07-27 at 7 12 54 pm](https://cloud.githubusercontent.com/assets/2011812/8923187/09196f06-350b-11e5-9c76-b5ce777e76aa.png)

**Comment by marcoherbst** [comment]
@affan00  ... could you take this? @muneeb2542 will advise...

**Comment by affan00** [comment]
done
