### ISSUE TITLE
HLS doesn't work on iOS

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#614]
HLS is working for Safari on OSx, (we know it's HLS because the video source address is https://media.evercam.io/live/gpocam/index.m3u8?token=qoSoGPwrzLlE0ITuMa2Id_VbCGRYYGAfGJlVZVm_LfAOCvW2SQwtZRsyh59CV_bqKhxqjSqIivemvuey4x5kujOAmLk3fDK8pI8otoAWEcY= ).

But it doesn't work on iOS - tried both Chrome and Safari, see screenshot attached.

@marcoherbst @mosic 

![img_4649](https://cloud.githubusercontent.com/assets/5046761/8961162/88474db0-360b-11e5-8112-2fcecaef0314.jpg)

**Comment by mosic** [comment]
@liutingdu That's weird. Does the same HLS stream work on Android?

Btw we use [videojs](https://github.com/videojs/videojs-contrib-hls) for this, there doesn't seem to be a known issue with playing on iOS at the moment.

**Comment by liutingdu** [comment]
@mosic Just tried it on Android, it's showing the same error, that's strange. Did it work for you on mobile before?

**Comment by marcoherbst** [comment]
@mosic , we dont know. We dont think (me and LD) that we ever tested it.

I do have it in mind that it was working on iOS though as I remember this
being an ongoing issue.

M

On 29 July 2015 at 16:50, Liuting Du <notifications@github.com> wrote:

> @mosic <https://github.com/mosic> Just tried it on Android, it's showing
> the same error, that's strange. Did it work for you on mobile before?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/614#issuecomment-125996225>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@liutingdu I thought it did, but now I'm not so certain. This may have something to do with the mime/source type we send to players, but it's still weird that it works on Safari without flash and not on iOS Safari.

@azharmalik3 Are you aware of any regressions in this area recently? I'll assign this to you but feel free to reassign to me if you don't manage to make it work for both desktop and mobile browsers.

**Comment by marcoherbst** [comment]
@azharmalik3  .... we have seen that http://www.carrollsirishgifts.com/livedublinwebcam DOES work on Android & iPhone .... so the problem in this ticket is definitely to do with our player in the dashboard.

I had dreamt that this would be built in a way that the same code was being used in our live widget (carrolls) as is used in dash .... clearly this isn't the case, but I haven't given up on the dream, until you tell me it's not practical.

M

**Comment by marcoherbst** [comment]
Update:
1. It seems we need to "click to play" ... that should be got rid of, we solved that on dash.evrcm already
2. Today, just now, it didnt work on my android & LDs iOS but did work on PC Chrome. I suspect this is not a clientside issue, but would like more info if you gather it. @azharmalik3

**Comment by azharmalik3** [comment]
@mosic @marcoherbst 
I investigated RTMP and HLS video on PC Chrome, Android and iOS. Found that html5 player support HLS video on all platforms but RTMP does not support on Android and iOS. 
![screenshot_2015-07-30-16-10-29](https://cloud.githubusercontent.com/assets/6176136/8982185/3120e424-36d8-11e5-93f2-ddc7627c1871.png)


Try different solutions to fix this issue:
1. adding mime-type in ruby 
2. change mime-type
3. jwplayer and VLC player

**Comment by marcoherbst** [comment]
Yes, that sounds right. Reason: no flash in mobile..

But, the question is different. The question is why is HLS not working on
our dashboard but it is working with our live view widget.

Get it? Get me on Skype if you want.

M

On 30 July 2015 at 12:30, Azhar Malik <notifications@github.com> wrote:

> @mosic <https://github.com/mosic> @marcoherbst
> <https://github.com/marcoherbst>
> I investigated RTMP and HLS video on PC Chrome, Android and iOS. Found
> that html5 player support HLS video on all platforms but RTMP does not
> support on Android and iOS.
> [image: screenshot_2015-07-30-16-10-29]
> <https://cloud.githubusercontent.com/assets/6176136/8982185/3120e424-36d8-11e5-93f2-ddc7627c1871.png>
>
> Try different solutions to fix this issue:
> 1. adding mime-type in ruby
> 2. change mime-type
> 3. jwplayer and VLC player
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/614#issuecomment-126279499>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
@marcoherbst i tested HLS and it works on both dashboard live view tab and widget. We are using same code on dashboard live view tab and live view widget for HLS.

**Comment by marcoherbst** [comment]
You think that dashboard hls is working on android chrome?  Can I see a
screenshot @azharmalik3

**Comment by azharmalik3** [comment]
@marcoherbst yes.

![screenshot_2015-07-30-16-10-29](https://cloud.githubusercontent.com/assets/6176136/8982185/3120e424-36d8-11e5-93f2-ddc7627c1871.png)

**Comment by marcoherbst** [comment]
@liutingdu  could you see if this is still valid? And if so, brief and assign the most suitable person (will be either Milos or Muneeb I guess.)

**Comment by liutingdu** [comment]
Tried it again on iOS and it's working! I'll close this
