### ISSUE TITLE
Live View Widget: Force JPG view for Evercam Play

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#622]
Currently the videojs&HLS doesn't work in some Android webview. A temporary fix is to  force load JPG view instead of video stream if it detects the request is from the Android app(Evercam Play)

References: 
http://stackoverflow.com/questions/6783185/detect-inside-android-browser-or-webview
It's the official recommended way to detect app webview : http://developer.android.com/guide/webapps/webview.html#EnablingJavaScript

Changes required on the live widget are: 
- Add a javascript function to detect Evercam Play's user agent, something like this:
```
function() isNativeApp{
    return /io.evercam.androidapp\/[0-9\.]+$/.test(navigator.userAgent);
}
```
(In my Android app I'll append 'io.evercam.androidapp/1.0' in webview's user agent)
- If it returns true, skip video stream and force it to play the JPG view.

**Comment by muneeb2542** [comment]
This issue is irrelevant now.
