### ISSUE TITLE
liveview widget seems to be playing RTSP (or trying to) even if there's no RTSP port ??

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#623]
See the problem here:

http://www.evercam.io/public/cameras/tower_cam

M

**Comment by azharmalik3** [comment]
@marcoherbst functionality already implemented to don't load RTSP if there is no RTSP port. Only issue is that camera does not have information about IP and ports when camera is shared with minimal access rights. So in this case we consider camera RTSP url is working.

**Comment by marcoherbst** [comment]
ok, @milos will you explain how this should be handled. I guess it's via
the RTMP field. When you do, let liuting know too ... she needs the same
info.

M

On 28 August 2015 at 12:06, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> functionality already
> implemented to don't load RTSP if there is no RTSP port. Only issue is that
> camera does not have information about IP and ports when camera is shared
> with minimal access rights. So in this case we consider camera RTSP url is
> working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/623#issuecomment-135742263>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
Fixed.
