### ISSUE TITLE
Camera shared email for UBNT cam arrived with a broken thumbnail

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#624]
![screenshot 2015-08-12 10 49 54](https://cloud.githubusercontent.com/assets/5648894/9221199/4d45b4ec-40e0-11e5-91fc-6eff1dae624a.png)

**Comment by marcoherbst** [comment]
@azharmalik3  ... I've tagged @muneeb2542  ... this is not at all urgent, but I thought it might be a nice one to look at? What do you think?

**Comment by azharmalik3** [comment]
Yes it's good task for him.

On Mon, Oct 12, 2015 at 1:38 PM, Marco Herbst <notifications@github.com>
wrote:

> @azharmalik3 <https://github.com/azharmalik3> ... I've tagged @muneeb2542
> <https://github.com/muneeb2542> ... this is not at all urgent, but I
> thought it might be a nice one to look at? What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/624#issuecomment-147329580>
> .
>



-- 
Azhar Malik
Senior Software Engineer
Evercam.io
Phone: +92 322 624 8204
Skype: azharmalik3
Email: http://www.evercam.io <http://www.evercam.io/team>

**Comment by muneeb2542** [comment]
This issue is already fixed.As you can see in the image
![screenshot from 2015-11-27 18-17-34](https://cloud.githubusercontent.com/assets/6482077/11442032/70f5fdd2-9533-11e5-8dc4-acdce3374b41.png)
