### ISSUE TITLE
In edit camera details, when I change the make/model it does not update the snapshot URL.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#627]

**Comment by marcoherbst** [comment]
There's a few things here.

1. If user has selected a make/model then it MUST use the URLs we have for that make./model.
2. It should be east to choose "Custom" .. write some info and add another URL.

MH ... Get your act together and specify this once and for all, properly, you ass.

**Comment by muneeb2542** [comment]
@marcoherbst the snapshot URL automatically changes whenever a different model is selected.
Do you want something more on edit camera ?

**Comment by muneeb2542** [comment]
@marcoherbst the snapshot URL automatically changes whenever a different model is selected.
Do you want something more on edit camera?

**Comment by marcoherbst** [comment]
You're right. It's done.
