### ISSUE TITLE
Remove URLS from /details page

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#628]
Remove the whole section "URLS", it was a bad idea.

EXCEPT , keep Base Cameras URL , if it is a camera that we own.

**Comment by marcoherbst** [comment]
@asimism  ... It seems that in the recent deploy we also removed the base-URL. Could you get it back please. For cameras that are owned and shared with full-rights. Well spotted @vinnieq

**Comment by asimism** [comment]
will do,
Asim

**Comment by marcoherbst** [comment]
@asimism  ... just a reminder about this issue.

**Comment by asimism** [comment]
Done and tested
