### ISSUE TITLE
Design improvements on Motion Tab

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#629]
- [x] Spelling on notification: - "Please" is misspelt.
- [x] Use toggle switches. Ask Marco.
- [x] The red border from Camba was nicer.
- [x] A refresh button after "Select area to be analysed for motion" to get a new snapshot.

**Comment by muneeb2542** [comment]
@marcoherbst For what purpose should a toggle switch be used in motion detection panel?

**Comment by muneeb2542** [comment]
@marcoherbst All the other things needed for design improvement are done.I wanted to ask for what purpose a toggle button should be add in the motion detection panel and where in the panel?

**Comment by muneeb2542** [comment]
All the design improvement are added now
