### ISSUE TITLE
Changes to Archives Page

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#630]
1. If there are no archives, I just want the text: "There are no archives" ... with no table.

2. Fix the broken navigation on the table when there are clips. (see screenshot).

![screenshot-dash evercam io 2015-08-18 21-43-30](https://cloud.githubusercontent.com/assets/5648894/9342252/8d5e73ae-45f2-11e5-8bd2-1cc4264b88ba.png)

**Comment by asimism** [comment]
done two things
1. Removed the table and leave the message when no clips in archive tab
2. Removed default arrows of table and left the ones that actually work.

**Comment by marcoherbst** [comment]
Nice.

On 23 September 2015 at 10:25, asimism <notifications@github.com> wrote:

> Closed #630 <https://github.com/evercam/evercam-dashboard/issues/630>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/630#event-416756460>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
