### ISSUE TITLE
A top of dashboard, when you click on a camera name, you can move between cameras ... improve this.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#635]
This is currently full-width. It shouldn't be. Also it should include thumbnails and status (continue to hide offline cameras if they are specified as hidden).

Take heavy inspiration from @shakeelanjum 's design on http://timelapse.evercam.io/ (see screenshot)

![screenshot-timelapse evercam io 2015-08-18 22-22-16](https://cloud.githubusercontent.com/assets/5648894/9343125/f7865f8a-45f7-11e5-9cca-a0d063bb324d.png)

**Comment by asimism** [comment]
@marcoherbst  Current pull request only contains the small improvement to this ie camera list is no more full width. In a next update we will add camera thumbnails.

**Comment by marcoherbst** [comment]
That sounds fine.

I wouldn't be surprised if we discover that the API endpoints for thumbnails are not yet fast enough ... but we might be pleasantly surprised. I know that this has been discussed by @shankardevy and @mosic .

M

**Comment by asimism** [comment]
I don't think we need fresh thumnails for this purpose it will be another
heavy lifting to send so many requests just to show a list of cameras.
There can be:
1. We have saved thumnail locally and just use them.
2. Another possible API end point where just one request can get all
images/thumbnails for all camera from a particular user.

**Comment by muneeb2542** [comment]
The Thumbnails are added to the camera list and the list is now long.Plus i have made some changes that broken image will not appear.Some broken image work is left for the details page but it will be deployed soon.
