### ISSUE TITLE
Remove all the Internal ports info from the dashboard on /details and on edit details.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#649]
on /details

**Comment by vinnieq** [comment]
Does local IP not provide for viewing the stream from within the local
network?

v



Evercam.io <http://www.evercam.io/> - Cameras Unleashed
Mobile (Irl) : +353 87 987 1869
ie.linkedin.com/in/vinniequinn
@vinniequinn  / @evrcm

**Comment by marcoherbst** [comment]
We used to use the local IP on Camba.tv website and on the Android App.

Then, we made a decision about a year ago to stream ALL media via the
Evercam server and not communicate at all between client (web/android) and
camera.

We did that in order to simplify the architecture ... it was one less route
to worry about.

M



On 2 September 2015 at 09:20, Vinnieq <notifications@github.com> wrote:

> Does local IP not provide for viewing the stream from within the local
> network?
>
> v
>
>
>
> Evercam.io <http://www.evercam.io/> - Cameras Unleashed
> Mobile (Irl) : +353 87 987 1869
> ie.linkedin.com/in/vinniequinn
> @vinniequinn / @evrcm
>
> On 1 September 2015 at 19:11, Marco Herbst <notifications@github.com>
> wrote:
>
> > on /details
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/evercam/evercam-dashboard/issues/649>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/649#issuecomment-136973933>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by asimism** [comment]
Is it not a replica of issue 628 ?

**Comment by marcoherbst** [comment]
This is related to Adding / Editing camera details. The point here is that we no longer need any Local IP or Port info.

We're keeping it in the API as additional details, but removing it from the dashboard. 

Make sense?

( #628 was about displaying URLs , similar, but different )

**Comment by marcoherbst** [comment]
@asimism hopefully the new issue name is now clearer.

**Comment by asimism** [comment]
Done and Tested
