### ISSUE TITLE
Live view widget full screen video view is half black

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#650]
While using the live view widget, after clicking the full screen icon, it becomes full screen but is half black (See screenshot).

<img width="1440" alt="screen shot 2015-09-01 at 09 11 20" src="https://cloud.githubusercontent.com/assets/5046761/9626375/0f46fdec-5155-11e5-9a08-20ec237380fd.png">

HTML page to reproduce this: 
```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Camera</title>
</head>
<body>
<div id='ec-container-wwcam'></div>
<script src='https://dash.evercam.io/live.view.widget.js?refresh=1&camera=wwcam&private=false' async></script>
</body>
</html>
```

**Comment by asimism** [comment]
fixed full view mode. Checked on wicklow cam site.

**Comment by marcoherbst** [comment]
Great work. The other place to test this is:
https://dash.evercam.io/widgets-new ... where it is also working. Nice. ( I
tested ).

On 23 September 2015 at 10:29, asimism <notifications@github.com> wrote:

> fixed full view mode. Checked on wicklow cam site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/650#issuecomment-142544400>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
