### ISSUE TITLE
Add PTZ interface to Dashboard

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#651]
@liutingdu would you mind filling in anything here that @azharmalik3 might want to know.

e.g.
* mobile-mast is a good camera to test on. 
* endpoints here: https://dash.evercam.io/swagger#!/cameras/POST_cameras_id_ptz_home_format
* anything else?

/cc @jgarciasacristan just FYI.

M

**Comment by liutingdu** [comment]
The PTZ functionalities that I implemented in E-Play are:

- Relative move left/right/up/down (```POST /cameras/{id}/ptz/relative??left=4``` same for right, up and down)
- Zoom in and out (```POST /cameras/{id}/ptz/relative??zoom=1```  ```POST /cameras/{id}/ptz/relative??zoom=-1```)
- Move to home (```POST /cameras/{id}/ptz/home```)
- Move to preset (```GET /cameras/{id}/ptz/presets``` and then ```POST /cameras/{id}/ptz/presets/go/{preset_token}```)
- Create a new preset (```POST /cameras/{id}/ptz/presets/create/{preset_name}```)

@azharmalik3  You can try it out by playing the camera mobile-mast in E-Play I've shared the camera with you.

Let me know if you have any questions :)

**Comment by liutingdu** [comment]
@azharmalik3 Forgot to mention that the PTZ buttons should only be visible when the camera model is onvif=true and ptz=true

**Comment by jgarciasacristan** [comment]
@liutingdu  @azharmalik3 The camera below is PTZ but it does not show the buttons in my android client. Is there a way to enable ONVIF and PTZ from the dashboard?

https://dash.evercam.io/v1/cameras/ballyguide-ptz/details

![image](https://cloud.githubusercontent.com/assets/8569388/9655637/7fd72840-522a-11e5-8ef5-6c164f26ae9c.png)

**Comment by marcoherbst** [comment]
Problem is that you're using the "Default" profile.

If the profile you need isn't there, let us know.

Or, choose one that has PTZ & Onvif. (like mobile-mast)

M

On 3 September 2015 at 10:58, jgarciasacristan <notifications@github.com>
wrote:

> @liutingdu <https://github.com/liutingdu> @azharmalik3
> <https://github.com/azharmalik3> The camera below is PTZ but it does not
> show the buttons in my android client. Is there a way to enable ONVIF and
> PTZ from the dashboard?
>
> https://dash.evercam.io/v1/cameras/ballyguide-ptz/details
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/8569388/9655637/7fd72840-522a-11e5-8ef5-6c164f26ae9c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/651#issuecomment-137396400>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by liutingdu** [comment]
@jgarciasacristan 

We don't have that camera's model in our database yet, I'll add it soon.

Please specify the model as "DS-2DF7286-A" for now.

**Comment by jgarciasacristan** [comment]
Thanks.  I was just wondering why the buttons were not shown in this one. Using mobile-mast instead.

**Comment by liutingdu** [comment]
@jgarciasacristan The new model has been added, just choose 'DS-2DF8223I-AEL' as model for the 'Mast Wicklow' camera. It's nice to have you help test the app on different cameras, thanks a lot :)
