### ISSUE TITLE
UP means down, down means UP ? on PTZ.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#657]
https://dash.evercam.io/v1/cameras/ballyguide-ptz

Seems the buttons are reversed.

This is for @azharmalik3 and would be ideally completed before end of day 9/9/2015

M

**Comment by mosic** [comment]
Maybe the camera is mounted upside down? :)

**Comment by marcoherbst** [comment]
Ha Ha. of course!!

I bet you're right.

I have to wait for daylight to be sure ....

M

On 8 September 2015 at 20:50, Miloš Mošić <notifications@github.com> wrote:

> Maybe the camera is mounted upside down? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/657#issuecomment-138681415>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
Marco i tested all ptz commands on different cams and these works fine.

Actually this camera is mounted upside down.

On Wed, Sep 9, 2015 at 1:05 AM, Marco Herbst <notifications@github.com>
wrote:

> Ha Ha. of course!!
>
> I bet you're right.
>
> I have to wait for daylight to be sure ....
>
> M
>
> On 8 September 2015 at 20:50, Miloš Mošić <notifications@github.com>
> wrote:
>
> > Maybe the camera is mounted upside down? :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/evercam/evercam-dashboard/issues/657#issuecomment-138681415
> >
> > .
> >
>
>
>
> --
> Marco Herbst
> *Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
> Mobile: +353 86 196 0451
> Skype: marco.a.herbst
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/657#issuecomment-138684538>
> .
>



-- 
Azhar Malik
Senior Software Engineer
Evercam.io
Phone: +92 322 624 8204
Skype: azharmalik3
Email: http://www.evercam.io <http://www.evercam.io/team>

**Comment by marcoherbst** [comment]
Excellent debugging ! :)

@jgarciasacristan here's a nice anecdote for your talk.

m

**Comment by jgarciasacristan** [comment]
LOL!
