### ISSUE TITLE
Snapshots are loaded via websockets even when the live view tab isn't selected

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#658]
The easiest way to fix this is to leave the snapshot websocket channel when another tab is focused and rejoin when live view is selected (only when JPG option is chosen).

**Comment by marcoherbst** [comment]
@asimism this looks like your reported issue.

**Comment by mosic** [comment]
Fixed in https://github.com/evercam/evercam-dashboard/pull/681.
