### ISSUE TITLE
PTZ Improvements

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#661]
[x] Increase PTZ controls size.
[  ] Ptz should work in fullscreen mode, including PRESETS.
[x] Add title over ptz buttons. 
[  ] Presets popup show scroll bar if height is more than page height.
[  ] Remove the white border around the presets box.
[  ]  Add "Waiting..." for 4 seconds, in the title bar, after each time the button is pressed, with animated . ... . ... ......
[  ] Make it all work on the widget
[  ] Default position should be top right corner.

**Comment by marcoherbst** [comment]
Good stuff @azharmalik3 and @liutingdu  , we'll pass this on now to @asimism

**Comment by asimism** [comment]
Are the PTZ controls live ? How can I view them ?

**Comment by azharmalik3** [comment]
Yes, it's live.

Do you have account on dashboard? Give me your evercam username i will
share PTZ camera with you.

On Mon, Sep 21, 2015 at 3:02 PM, asimism <notifications@github.com> wrote:

> Are the PTZ controls live ? How can I view them ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/661#issuecomment-141930447>
> .
>



-- 
Azhar Malik
Senior Software Engineer
Evercam.io
Phone: +92 322 624 8204
Skype: azharmalik3
Email: http://www.evercam.io <http://www.evercam.io/team>

**Comment by asimism** [comment]
Hi
I am using Marco's account.
Regards
Asim

**Comment by azharmalik3** [comment]
Following are PTZ cameras in Marco's account:
1) Mast Wicklow N B
2) Mobile Mast

On Mon, Sep 21, 2015 at 3:24 PM, asimism <notifications@github.com> wrote:

> Hi
> I am using Marco's account.
> Regards
> Asim
>
> On Mon, Sep 21, 2015 at 3:04 PM, Azhar Malik <notifications@github.com>
> wrote:
>
> > Yes, it's live.
> >
> > Do you have account on dashboard? Give me your evercam username i will
> > share PTZ camera with you.
> >
> > On Mon, Sep 21, 2015 at 3:02 PM, asimism <notifications@github.com>
> wrote:
> >
> > > Are the PTZ controls live ? How can I view them ?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/evercam/evercam-dashboard/issues/661#issuecomment-141930447
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Azhar Malik
> > Senior Software Engineer
> > Evercam.io
> > Phone: +92 322 624 8204
> > Skype: azharmalik3
> > Email: http://www.evercam.io <http://www.evercam.io/team>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/evercam/evercam-dashboard/issues/661#issuecomment-141930795
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/661#issuecomment-141934328>
> .
>



-- 
Azhar Malik
Senior Software Engineer
Evercam.io
Phone: +92 322 624 8204
Skype: azharmalik3
Email: http://www.evercam.io <http://www.evercam.io/team>

**Comment by asimism** [comment]
thanks, got it.

**Comment by asimism** [comment]
@azharmalik3 it seems like some items are already done. eg
[x] Increase PTZ controls size.
[x] Add title over ptz buttons. 
Could you please let me know what is already done ?

**Comment by azharmalik3** [comment]
@asimism
Marked [x] points are completed.
You can start work on other points which are not marked.

**Comment by asimism** [comment]
Done and tested
