### ISSUE TITLE
The offline camera icon on dashboard should be a toggle button. 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#664]
It should only be visible if there are offline cameras.
If there are, then this button toggles their visibility on and off.

**Comment by marcoherbst** [comment]
@asimism  ... nice one, but it should also change the cams that are displayed in the main panel ... currently it only impacts the sidebar.

**Comment by asimism** [comment]
OK got it, I thought it was just a filter for side bar list.

**Comment by marcoherbst** [comment]
I had in mind also to use a toggle button with an icon. 

I havent seen one that I really like, typically we stick to what we find in font-awesome, metronic & bootstrap ... but basically I'm thinking of the chap below, but using the broken chain.

![nexusae0_pin](https://cloud.githubusercontent.com/assets/5648894/10395445/e870805a-6e94-11e5-8c20-3d8de4190ba5.png)

**Comment by asimism** [comment]
Hi Marco
Yes I can use this toggle button but I think it will not fit well here. The
small text is more descriptive and looking nice. However if you insist I
will use this toggle button but blue color is bit alien here ?
Regards
Asim

**Comment by marcoherbst** [comment]
Nope, I'm also not happy with the toggle button suggestion , yet.

I think it's the right idea, but for now treat it just as a placeholder for
discussion. When you can, make the change to update the right hand pane and
we'll call the issue closed, unless someone pipes up with a better
interface suggestion.

M

On 9 October 2015 at 14:53, asimism <notifications@github.com> wrote:

> Hi Marco
> Yes I can use this toggle button but I think it will not fit well here. The
> small text is more descriptive and looking nice. However if you insist I
> will use this toggle button but blue color is bit alien here ?
> Regards
> Asim
>
> On Fri, Oct 9, 2015 at 6:50 PM, Marco Herbst <notifications@github.com>
> wrote:
>
> > I had in mind also to use a toggle button with an icon.
> >
> > I havent seen one that I really like, typically we stick to what we find
> > in font-awesome, metronic & bootstrap ... but basically I'm thinking of
> the
> > chap below, but using the broken chain.
> >
> > [image: nexusae0_pin]
> > <
> https://cloud.githubusercontent.com/assets/5648894/10395445/e870805a-6e94-11e5-8c20-3d8de4190ba5.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/evercam/evercam-dashboard/issues/664#issuecomment-146876488
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/664#issuecomment-146877539>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by asimism** [comment]
Right hand pane removes offline cameras when we click "hide offline", I am closing this ticket as per discussion above.

**Comment by asimism** [comment]
need to integrate with settings page

**Comment by muneeb2542** [comment]
@marcoherbst  do you want the toggle button instead of the online/offline message in the sidebar or do you want it instead of the checkbox in the settings panel?

**Comment by marcoherbst** [comment]
Replace both, please.

(Unless you have a better idea)

M

On 22 December 2015 at 05:56, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> do you want the toggle
> button instead of the online/offline message in the sidebar or do you want
> it instead of the checkbox in the settings panel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/664#issuecomment-166519315>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
@marcoherbst The toggle will look like this or do you want it some other style?
![screenshot from 2016-01-12 17-31-01](https://cloud.githubusercontent.com/assets/6482077/12263620/6f03dc7c-b952-11e5-9197-c8a196eed3eb.png)

**Comment by muneeb2542** [comment]
more like this?
![screenshot from 2016-01-12 18-09-38](https://cloud.githubusercontent.com/assets/6482077/12264338/fae75372-b957-11e5-8dc4-25326ee7e16c.png)

**Comment by marcoherbst** [comment]
yup

On 12 January 2016 at 13:12, Muneeb Rana <notifications@github.com> wrote:

> more like this?
> [image: screenshot from 2016-01-12 18-09-38]
> <https://cloud.githubusercontent.com/assets/6482077/12264338/fae75372-b957-11e5-8dc4-25326ee7e16c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/664#issuecomment-170907430>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by liutingdu** [comment]
Why are we using different toggles in camera list and in settings?  (See screenshots attached)

And I think the settings page is strange without text 'Hide offline cameras', it's ok to use the offline link icon in the side navigation to simplify the page, but in settings(The first screenshot) the user won't understand what the toggle means at all.
<img width="524" alt="screen shot 2016-01-13 at 12 06 00" src="https://cloud.githubusercontent.com/assets/5046761/12293837/14686660-b9ee-11e5-8b73-83b42872f0da.png">
<img width="241" alt="screen shot 2016-01-13 at 12 06 08" src="https://cloud.githubusercontent.com/assets/5046761/12293838/14692294-b9ee-11e5-822d-b7a78586de7d.png">

**Comment by marcoherbst** [comment]
Good stuff LD, Muneeb is aware and fixing it :)

m

On 13 January 2016 at 12:09, Liuting Du <notifications@github.com> wrote:

> Why are we using different toggles in camera list and in settings? (See
> screenshots attached)
>
> And I think the settings page is strange without text 'Hide offline
> cameras', it's ok to use the offline link icon in the side navigation to
> simplify the page, but in settings(The first screenshot) the user won't
> understand what the toggle means at all.
> [image: screen shot 2016-01-13 at 12 06 00]
> <https://cloud.githubusercontent.com/assets/5046761/12293837/14686660-b9ee-11e5-8b73-83b42872f0da.png>
> [image: screen shot 2016-01-13 at 12 06 08]
> <https://cloud.githubusercontent.com/assets/5046761/12293838/14692294-b9ee-11e5-822d-b7a78586de7d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/664#issuecomment-171272807>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
The toggle is fixed now.

**Comment by muneeb2542** [comment]
Plus text is also now added with the settings toggle.
