### ISSUE TITLE
Use Service Workers to handle offline events

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#668]
Seems to me that this is related to 

https://developers.google.com/web/fundamentals/getting-started/primers/service-workers

**Comment by marcoherbst** [comment]
![screenshot 2015-09-15 10 42 27](https://cloud.githubusercontent.com/assets/5648894/9873269/825adbdc-5b96-11e5-9b92-7e134a569d0a.png)


This error page seems a little too general......

**Comment by marcoherbst** [comment]
This is a tip from Eugene (I've not yet watched it) relating to letting certain things fail without effecting other things:  https://www.youtube.com/watch?v=xsSnOQynTHs

@mosic  you brought up the idea previously of the dashboard being more standalone in this way. We're mixing 2 ideas here ... independence & better failing , is that an ok thing to do ? and, if you can improve this ticket, feel free.

**Comment by mosic** [comment]
Dan is a great developer and that's an awesome talk, but I'm not sure how it can be applied to this issue, it revolves around having a nice development experience. Any specific ideas @eugenehp ?

In the meantime, I added a simple checking and reloading to the dashboard's error page in https://github.com/evercam/evercam-dashboard/pull/671

You can see how it looks at https://dash.evercam.io/500 but by opening the error page directly you won't be redirected to the page you were previously on, it will just reload the same error page over and over.

**Comment by marcoherbst** [comment]
@affan00  , not urgent, but I think it's a good one for you.

**Comment by marcoherbst** [comment]
Putting this to October, I've forgotten its purpose. Discuss & then kill or do.

**Comment by affan00** [comment]
This issue was related to auto update the left navigation camera status without refreshing the page in any case if the camera comes online or goes offline. This issue has already been fixed, So I am closing this now.
