### ISSUE TITLE
RTSP live view doesn't work with Safari on Mac (OSX)

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#673]
It's showing error "No compatible source was found for this video" (See screenshot attached)

<img width="1440" alt="screen shot 2015-09-18 at 17 31 03" src="https://cloud.githubusercontent.com/assets/5046761/9964968/3f464d6c-5e2b-11e5-83ca-77e9ca559b36.png">

**Comment by marcoherbst** [comment]
@liutingdu  would you check this again ? My guess is that it's fixed.

m

**Comment by liutingdu** [comment]
It's working now: 

![screen shot 2016-03-03 at 09 30 19](https://cloud.githubusercontent.com/assets/5046761/13490124/a8801bee-e122-11e5-8ca0-fb48c5f4d0ab.png)
