### ISSUE TITLE
Add Camera page improvements

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#682]
1. Make https://dash.evercam.io/v1/cameras/new to be consistent with http://evercam.io/#add-camera, the following things will be involved for the dashboard:
   - Use the same layout
   - Show the vendor logo and the model thumbnail
   - Remove camera ID  
   - Auto populate model 'Default' if a vendor is selected (Currently it's populating a random model)
2. There are some additional changes should be made to both Add Camera pages for the dashboard and the public site (They are done in the Android app)
   - The dropdown icon should be clickable, it should show/hide the dropdown list when clicked.
   - Add RTSP port and RTSP path
   - Hide RTSP path and snapshot path if a specific model is selected
   - A bug: The model thumbnail is scaled incorrectly. It should keep the original ratio (See screenshot)

<img width="570" alt="screen shot 2015-09-25 at 14 55 38" src="https://cloud.githubusercontent.com/assets/5046761/10102302/8d2f8ce0-6395-11e5-8227-23e74633c73a.png">

**Comment by marcoherbst** [comment]
Not relevant
