### ISSUE TITLE
Check port is open/closed when add & edit camera

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#686]
This is related to add/edit camera page improvements https://github.com/evercam/evercam-dashboard/issues/682

It's done in Android: https://github.com/evercam/evercam-play-android/issues/102

When user types in the HTTP/RTSP port, it should check port status by sending request to API 
```GET https://api.evercam.io/portcheck?ip=89.101.222.333&port=80```
It should return true if the port is open and otherwise return false  

The details are:
- Launch the port check when HTTP/RTSP port field or external IP address field lost focus, and show 'Port is open' or 'Port is closed' based on the result
- Clear the port status when the value for HTTP/RTSP port/IP address field is changed

**Comment by marcoherbst** [comment]
Good.

It's not immediately obvious to me that we need to use the API you suggest
and not a call from the evercam API .... but, anyhow, this is a good
placeholder.

M

On 28 September 2015 at 14:30, Liuting Du <notifications@github.com> wrote:

> This is related to add/edit camera page improvements #682
> <https://github.com/evercam/evercam-dashboard/issues/682>
>
> It's done in Android: evercam/evercam-play-android#102
> <https://github.com/evercam/evercam-play-android/issues/102>
>
> When user types in the HTTP/RTSP port, it should check port status by
> sending request to API http://tuq.in/tools/port
>
> The details are:
>
>    - Launch the port check when HTTP/RTSP port field or external IP
>    address field lost focus, and show 'Port is open' or 'Port is closed' based
>    on the result
>    - Clear the port status when the value for HTTP/RTSP port/IP address
>    field is changed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/686>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
It is done.

The port inputs needs accept only numbers.Will make the changes shortly.
