### ISSUE TITLE
Favicon is poorly displayed or missing on Dashboard (Chrome).

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#688]
@asimism , despite this being a seemingly small, trivial task, I'd like it to be given some careful consideration. I have a hunch that we've dealt with favicons differently across different repos (check out evercam-public ) and have, in places, duplicated how it's handled. I've seen it in our codebase as base-64 encoded within a header template, referred to via an img-url and also available as a .ico file that's not referenced.

Either way, please take the time to find out how this should be done best, understand how our similar assets are currently stored and feel free to ask @marcoherbst to provide alternative versions with different resolutions.

If you are able to propose a solution that works across all relevant repos, that would be a bonus. ( evercam-public , evercam-gateway-dashboard )

**Comment by mosic** [comment]
I'd actually like to spend an hour or less on this today/tomorrow as this was bothering me personally for a while.

**Comment by marcoherbst** [comment]
Great, that's perfect.

**Comment by mosic** [comment]
Update - this is done and deployed on the dashboard, I'll make a pull request for the public site today too.

**Comment by mosic** [comment]
Done, I updated `evercam-dashboard` and made pull requests to `evercam-public-site` and `evercam-gateway-dashboard`.
