### ISSUE TITLE
Access_token table need cleanup. (user have lot of records against one app like timelapse)

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#699]
On each authentication system save new auth_token in database. is this right? or not?

**Comment by mosic** [comment]
Yes, that's right as far as I know. That's one of the reasons the authorization flow is inefficient, it needs to look at all existing tokens to check if someone is authorized or not.

**Comment by marcoherbst** [comment]
@mosic  @azharmalik3 , am I right that as of today, we have no OAuth functionality left being used in Evercam ... we could create a task for @muneeb2542 to remove all traces of OAuth from the entire app ... including DB, Dashboard, API ... everywhere ... yes?

**Comment by mosic** [comment]
@marcoherbst Yes, that's right. (Cambase uses OAuth, but that's not important)

**Comment by marcoherbst** [comment]
Great. 
Replacing it with: https://github.com/evercam/evercam-dashboard/issues/1126
