### ISSUE TITLE
Billing minor changes 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#707]
- [x] Annual price = Monthly price *10
- [x] text " ( Total = X ) " Alongside Licences Required and Licences Purchased. Green if all ok, red if not ok.
- [x] Banner at top, central, vertically aligned with "Licences Required" to say " You require additional licences " if necessary.
- [x] Use border around the Licences Purchased area.

**Comment by azharmalik3** [comment]
Made total red/green for licences required and purchased.
