### ISSUE TITLE
/shares needs to be responsive

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#713]
It doesn't shrink well to mobile screens.

@liutingdu  may also want to make a comment about how this will be used within her android webview. I suspect there's a ticket out there for this already.

M

**Comment by asimism** [comment]
@liutingdu is there any thing special I need to be aware of when I make it responsive ?

**Comment by liutingdu** [comment]
This is the Android app's ticket: https://github.com/evercam/evercam-play-android/issues/72

I couldn't think of anything special around the UI, as it explained in that ticket, the problem is related to authentication.

**Comment by asimism** [comment]
Tested online
