### ISSUE TITLE
Time to load /billing page on account "Marco" ... toooooo slloooooooow

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#715]

**Comment by azharmalik3** [comment]
@marcoherbst Made some improvements and remove redundant calls to stripe api, also load history tables using ajax. Could you please check billing page once again.

**Comment by marcoherbst** [comment]
Still , for me, about 6 seconds to load billing page for user "marco".
Also, when I update my plans, there is about 6 seconds after I click "save".

I think a target should be less than 1 second.

M

On 13 October 2015 at 06:54, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> Made some improvements and
> remove redundant calls to stripe api, also load history tables using ajax.
> Could you please check billing page once again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/715#issuecomment-147613690>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by marcoherbst** [comment]
well done.
