### ISSUE TITLE
Billing emails - why two?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#719]
One is called "Evercam.io receipt" and comes from stripe. Fine.
One is called "Payment invoice" and comes from sendgrid.

Seems to me we dont need the sendgrid one?

@azharmalik3  ... anything more to add here? What was the story with sendwithus ?

M

**Comment by azharmalik3** [comment]
@marcoherbst i don't know why we are using sendwithus thired party for sending stripe email. I think we don't need this.

**Comment by marcoherbst** [comment]
Great, remove it.
M

On 12 October 2015 at 14:43, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> i don't know why we are
> using sendwithus thired party for sending stripe email. I think we don't
> need this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/719#issuecomment-147403614>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
https://github.com/evercam/evercam-dashboard/issues/709
