### ISSUE TITLE
Download image from recordings - Remove the 'download' attribute for Android app client

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#727]
Currently the download image from recordings doesn't work in Android app, as discussed in: https://github.com/evercam/evercam-play-android/issues/96

This task is about removing the ```<a>``` 'download' attribute for the Android client in [JavaScript code](https://github.com/evercam/evercam-dashboard/blob/510f595ea92bb24a4b53b114e224edad3ad288e6/app/assets/javascripts/saveimage.js) of saving image. 

This would be the method to check if it's the Android app client or not:

```
function() isNativeApp{
    return /io.evercam.androidapp\/[0-9\.]+$/.test(navigator.userAgent);
}
```

Let me know if there are any questions :) 

Liuting

**Comment by muneeb2542** [comment]
i am in the process of starting evercam-dashboard locally on my pc.As soon as it starts i will definitely look into it and inform you.

**Comment by muneeb2542** [comment]
@liutingdu well i wanted to ask that do you want to disable save image icon on evercam-android play or do you want completely remove it from the app?

**Comment by muneeb2542** [comment]
@liutingdu i have removed the download attribute from android app client and will deploy it asap.

**Comment by liutingdu** [comment]
@muneeb2542 Thanks :) I'll test it when it gets deployed.

I think removing the download attribute would be enough, but I need to make further changes on Android before knowing it works or not

**Comment by liutingdu** [comment]
@muneeb2542 Seems this is not deployed yet? Any updates?

I'll reopen this for now. The issue shouldn't be closed until it's deployed and tested.

**Comment by muneeb2542** [comment]
@liutingdu i just merged my pull request , so hopefully it will be deployed shortly

**Comment by muneeb2542** [comment]
@liutingdu i just tested this through widget and through my mobile,it works fine.So i am closing this issue

**Comment by liutingdu** [comment]
@muneeb2542 Is this the only change you made?  https://github.com/evercam/evercam-dashboard/commit/86d8cb3a4cbb31768ae025a288527f66d0deced1

I tested it in my app and it doesn't work as expected. I think you didn't understand the issue correctly. It's not about hiding the button on smaller screen. Please double check the issue description, the button shouldn't be hidden. This is the 'download attribute': https://github.com/evercam/evercam-dashboard/blob/510f595ea92bb24a4b53b114e224edad3ad288e6/app/assets/javascripts/saveimage.js#L19

Please let me know if you have any question about this.

**Comment by muneeb2542** [comment]
@liutingdu well that is what i was confused about in the start ,do you want to remove the download button altogether or do you want to disable it because both of these things can be done on 2 levels.
Whether we do it on the css level or we add new script to it.

So please elaborate do you want the changes on user level or at the backend?

**Comment by liutingdu** [comment]
@muneeb2542 

It's not about removing the download button, it's about remove the ```download``` attribute in the code for Android client, but keep that button. It should be done by making changes in the JavaScript code, something like: 

```
function() isNativeApp{
    return /io.evercam.androidapp\/[0-9\.]+$/.test(navigator.userAgent);
}

if(!isNativeApp()){
   // Keep the download attribute for other clients
   save.download = fileName || 'unknown';
}
else{
   // Don't add the download attribute if it's the Android client
}
```

Let me know if you are still confused, we can talk on Skype if it helps :)

**Comment by muneeb2542** [comment]
@liutingdu  As you asked me i have removed the download attribute for through the same procedure that you told me about.I have tested it on my mobile and when i touch the download button,the image opens but it is not saved.

Let me know about it when you test it on the App.

**Comment by liutingdu** [comment]
Hi @muneeb2542,

Thanks for the update.

'The image opens but not saved' is the expected behaviour, I need to make further change in the app to trigger the download (see https://github.com/evercam/evercam-play-android/issues/96)

I see from [your code](https://github.com/evercam/evercam-dashboard/blob/8289415146477af6309765733ad58bdc8a7d56c3/app/assets/javascripts/saveimage.js#L16) that you check string 'Android' in user agent. By doing this it disables the download for Chrome on Android too. 

This task is about Android app, not browser on Android(eg. Chrome). when user opens the widget from Android Chrome, it should keep the download attribute. If user uses the widget from [our Android app](https://play.google.com/store/apps/details?id=io.evercam.androidapp&hl=en) This method should be used, instead of simply check the string 'Android'. It's the only way to recognise our Android app.
```
function() isNativeApp{
    return /io.evercam.androidapp\/[0-9\.]+$/.test(navigator.userAgent);
}
```

Please make this change and let me know if you don't get the difference between Android app WebView and Android Chrome.

**Comment by muneeb2542** [comment]
@liutingdu i have made the appropriate changes and deployed it.After testing it i have found that it works fine on Android Chrome whereas the image opens in the App.

Please let me know as soon as you test it.

**Comment by liutingdu** [comment]
@muneeb2542 Thanks, now it works as expected :) 

I'll make more changes on Android later
