### ISSUE TITLE
Better height management on live view to avoid having vertical scrollbar.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#730]
This is a good example of where the vertical scrollbar seems unnecessary:

![screenshot 2015-10-17 10 03 52](https://cloud.githubusercontent.com/assets/5648894/10557935/859bb30a-74b6-11e5-997f-9bdd1bbd4950.png)

**Comment by muneeb2542** [comment]
@marcoherbst the scroll bar only appears when you have the option to change between feeds of a video,if there is only one feed type then the scroll bar does not appear.The live-view already appears with good height management or do you want me to place each and everything in one placeholder?

**Comment by marcoherbst** [comment]
I get your point, but:

On my monitor, jpeg view leaves about 20 white pixels height unused at the bottom of the screen and on rtsp view I crop the image by about 30 pixels (and then below that is the select box).

That would be worth fixing.

re: The select box, do you think it would be possible to have the select box overlayed on top of the image, also in the bottom right corner, like we do for snapshot & pause? If so, then please make a ticket for that. NB it would have to work for jpeg player and video.js , of course, but this would allow us to get rid of the scroll bar altogether.

**Comment by muneeb2542** [comment]
yes this is possible and i made a new ticket for it.

**Comment by muneeb2542** [comment]
@marcoherbst  i have tried alot and the only way of removing the unused space on the bottom is making video size bigger but that would create a horizontal scroll bar as the video would be bigger than the associated screen size.so i have cleared some of the space but some still remains.
