### ISSUE TITLE
/Sharing interface changes

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#734]
Name == "Shared With"

Replace username with email.

On Shared By column should have the same format, i.e.:

First Name Last Name
email

and then we can remove the column "Email".

Also, could you use an icon instead of "Remove", I guess a trashbin from fontawesome.

@azharmalik3  sorry !  

M

**Comment by azharmalik3** [comment]
@marcoherbst remove username again?

**Comment by marcoherbst** [comment]
yup

On 22 October 2015 at 13:04, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> remove username again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/734#issuecomment-150201192>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
DONE
