### ISSUE TITLE
A custom payments option for logged in users

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#735]
Something along these lines:

![Uploading Custom Payments Dialog.jpg…]()

@azharmalik3  , could you tell me what issues this raises:

+ Billing history? will it work
+ How / where to show / edit / cancel existing subs
+  .. whatever else you can see ... I'm sure there will be problems here.

**Comment by marcoherbst** [comment]
![custom payments dialog](https://cloud.githubusercontent.com/assets/5648894/10642452/a7903532-7815-11e5-84af-cd6ae6cc1f35.jpg)

**Comment by azharmalik3** [comment]
@marcoherbst 
1) Billing history will work. (Tested)
`Subscription Payment` why we need this?

**Comment by marcoherbst** [comment]
@azharmalik3  ... we might consider passing responsibility for billing to @muneeb2542  ... or @affan00

**Comment by azharmalik3** [comment]
Already completed.
