### ISSUE TITLE
Username starts with number shouldn't get warning message

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#736]
I was creating an account with username starts with a number, see screenshot, it was showing an incorrect warning message. But when I click the button 'Create New Account', the account was successfully created.

<img width="690" alt="screen shot 2015-10-22 at 10 14 19" src="https://cloud.githubusercontent.com/assets/5046761/10661404/b7f3e83e-78a5-11e5-9714-f5cb2dfbe56b.png">

**Comment by muneeb2542** [comment]
this is fixed and deployed on the site.
