### ISSUE TITLE
Add Motion Detection Thumbnails below Recordings in /recordings

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#740]
I wonder, @azharmalik3  if this might be implementable now?

We've got MD values (full screen , default parameters) for each snapshot. You might be able to just pick the top few values (20? or 5%) and show them?

My guess is that this will require changes to the various snapshot endpoints, perhaps you'd look into this and see if you see a way ?

m

**Comment by azharmalik3** [comment]
MD stripe added in /recordings tab.
