### ISSUE TITLE
Get some stripe branding on to /pay 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#741]
to show we're down with the cool kid billionaires.
m

**Comment by marcoherbst** [comment]
@affan00  ... this is really easy. We just use a suitable logo from here: https://stripe.com/about/resources you could close this today ?

**Comment by affan00** [comment]
Yes Marco.

**Comment by affan00** [comment]
Marco, Where to place the "stripe" logo? with other cards logo(i-e visa,
master)?

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by affan00** [comment]
it's done.
