### ISSUE TITLE
when sharing a camera with a username that does not exist we need  a better message

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#743]
Invalid email address specified.

should be "That username doesn't seem to exist, or you've entered an invalid email address."

**Comment by muneeb2542** [comment]
This was a api issue and it is deployed.
![screenshot from 2015-11-21 03-12-18](https://cloud.githubusercontent.com/assets/6482077/11313315/c954eaa0-8ffd-11e5-987c-1bc40d37ea74.png)
