### ISSUE TITLE
Online / Offline ... we've got 2 toggles , one on the My Cameras area and one on Settings ... combine them.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#749]
@asimism  does this make sense? 

https://dash.evercam.io/v1/users/meherbst/settings

M

**Comment by asimism** [comment]
Yes, It does.

**Comment by asimism** [comment]
The best way to do this is:
1. If user have selected to hide offline cameras from settings page. Then
we will not show "show/hide link" on cameras page.
2. If user has selected to show offline cameras from settings page. Then we
show "show/hide link" on cameras page but it will not effect account
setting which is permanent (it saves a cookie on user's machine).
Is this workflow OK ?

**Comment by marcoherbst** [comment]
actually my intention was just that they duplicate each other.

Your toggle button has exactly the same functionality as the settings
checkbox. i.e. it uses the cookie.

That was actually the original intention, poorly specified. Seem ok?

I suspect, given the way we've gone about this, that there will be some
scope to clean up the code as it must now be kind of duplicated ?

m

On 27 October 2015 at 11:41, asimism <notifications@github.com> wrote:

> The best way to do this is:
> 1. If user have selected to hide offline cameras from settings page. Then
> we will not show "show/hide link" on cameras page.
> 2. If user has selected to show offline cameras from settings page. Then we
> show "show/hide link" on cameras page but it will not effect account
> setting which is permanent (it saves a cookie on user's machine).
> Is this workflow OK ?
>
>
> On Tue, Oct 27, 2015 at 3:40 PM, Marco Herbst <notifications@github.com>
> wrote:
>
> > @asimism <https://github.com/asimism> does this make sense?
> >
> > https://dash.evercam.io/v1/users/meherbst/settings
> >
> > M
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/evercam/evercam-dashboard/issues/749>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/749#issuecomment-151464389>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by asimism** [comment]
No, Our code does not write a cookie, Only settings button does. Our code
only hide/unhide html using Jquery and css it has nothing to do with
existing functionality on settings page. So there is no duplication of
code. Please comment again on my workflow based on this new information.

**Comment by marcoherbst** [comment]
I'm sticking to the same story.
Replace jquery method with the cookie method.
Functionality should also duplicate the checkbox functionality.
M

On 27 October 2015 at 11:50, asimism <notifications@github.com> wrote:

> No, Our code does not write a cookie, Only settings button does. Our code
> only hide/unhide html using Jquery and css it has nothing to do with
> existing functionality on settings page. So there is no duplication of
> code. Please comment again on my workflow based on this new information.
>
> On Tue, Oct 27, 2015 at 4:46 PM, Marco Herbst <notifications@github.com>
>
> wrote:
>
> > actually my intention was just that they duplicate each other.
> >
> > Your toggle button has exactly the same functionality as the settings
> > checkbox. i.e. it uses the cookie.
> >
> > That was actually the original intention, poorly specified. Seem ok?
> >
> > I suspect, given the way we've gone about this, that there will be some
> > scope to clean up the code as it must now be kind of duplicated ?
> >
> > m
> >
> > On 27 October 2015 at 11:41, asimism <notifications@github.com> wrote:
> >
> > > The best way to do this is:
> > > 1. If user have selected to hide offline cameras from settings page.
> Then
> > > we will not show "show/hide link" on cameras page.
> > > 2. If user has selected to show offline cameras from settings page.
> Then
> > we
> > > show "show/hide link" on cameras page but it will not effect account
> > > setting which is permanent (it saves a cookie on user's machine).
> > > Is this workflow OK ?
> > >
> > >
> > > On Tue, Oct 27, 2015 at 3:40 PM, Marco Herbst <
> notifications@github.com>
> > > wrote:
> > >
> > > > @asimism <https://github.com/asimism> does this make sense?
> > > >
> > > > https://dash.evercam.io/v1/users/meherbst/settings
> > > >
> > > > M
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/evercam/evercam-dashboard/issues/749>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/evercam/evercam-dashboard/issues/749#issuecomment-151464389
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Marco Herbst
> > *Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
> > Mobile: +353 86 196 0451
> > Skype: marco.a.herbst
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/evercam/evercam-dashboard/issues/749#issuecomment-151465420
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/749#issuecomment-151467102>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by asimism** [comment]
Agreed !

**Comment by muneeb2542** [comment]
done
