### ISSUE TITLE
Some notes on Motion Detection Recordings Interface

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#754]
- [x]  There should be no padding of the grey border around the MD results thumbnail row.
- [x] Space the results to fill the row.
- [x] Put the times, in white, overlaid over the image.
- [x] Remove the text "Motion Detection Results" and get rid of that vertical white space.
- [x] After the notes (typically "Evercam Proxy" , put in  () the motion level ... this will be interesting until we get familiar with it.
- [x] While we're at it, let's put an icon over the image, top right corner to show/hide the calendar. Use fa-calendar

**Comment by faisal2472** [comment]
One more issue on MD when we select area .. 
its not given us offer to scroll down or extend selected area.

**Comment by marcoherbst** [comment]
@muneeb2542  any questions about this? Anything you cant do ?

**Comment by muneeb2542** [comment]
@marcoherbst  @affan00  is almost finished with this,Only 2 checks are left.
He has saved his work locally and no, i can do the rest also.

**Comment by marcoherbst** [comment]
@muneeb2542 Let's close this issue and put those last 2 items onto a new issue on Milestone "Long Finger" . Then we can close this milestone and you can pat yourself on the back.

**Comment by azharmalik3** [comment]
@affan00 Still not complete.
