### ISSUE TITLE
If I add No RTSP port or a closed RTSP port, it tried, but fails to load the rtsp stream - it should revert to jpeg. 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#759]
@mosic can you come up with something better?

**Comment by marcoherbst** [comment]
This raised its head again recently with Central Bank. We had model "Hikvision" and no RTSP port (we may have had the port set and then removed it). The widget kept trying to load the RTMP stream, but of course couldn't. 

I think it's obvious that the behaviour we want is - if there's no working stream then use the jpegs. @mosic , you might make the suggestion as to how this should be implemented and then pass this ticket on to someone else.

**Comment by marcoherbst** [comment]
Or if the RTSP port is zero. @mosic

**Comment by mosic** [comment]
Today I made a change to not expose RTMP/HLS streams if the port isn't explicitly set or is set to 0.

We can add the closed port check as more things are moved to evercam-media, evercam-api and dashboard don't talk directly to the cameras so there's no way to decide at that point whether to display video or not.

**Comment by marcoherbst** [comment]
@mosic  I'm not clear. Should this issue, here in -dash, now be closed ?

**Comment by mosic** [comment]
@marcoherbst Yes, I think so.
