### ISSUE TITLE
Many "/undefined" 404 errors in the logs

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#770]
We're getting lots of requests to `/undefined` path (for example `/undefined&1446751080915`), it looks like it's caused by a bug in the live view widget.

Btw there are many different ip addresses from which these requests are coming from so it's not just bug in some of the client's code.

**Comment by marcoherbst** [comment]
@azharmalik3  , I know this is a deviation from your current plan, but if you thought you could tackle this one ASAP it would be lovely to get to the bottom of it. @mosic , does Azhar need some explanation about websockets before tackling this or does he already know enough or it's not relevant ?

**Comment by mosic** [comment]
@marcoherbst I don't think it's relevant here as we're using websockets only on the live view tab inside the dashboard, and not on the live view widgets.

**Comment by marcoherbst** [comment]
Right, so why not use them on the widgets? Isn't that kind of the point ?
that the dashboard (at least in theory) is built on the widgets?

M

On 5 November 2015 at 19:57, Miloš Mošić <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> I don't think it's relevant
> here as we're using websockets only on the live view tab inside the
> dashboard, and not on the live view widgets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/770#issuecomment-154173161>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
That's the plan, we just haven't gotten to it :)

**Comment by marcoherbst** [comment]
Ok, @mosic is making an issue on evercam-media to do the necessary work for
this in the future

http://caniuse.com/#feat=websockets

@azharmalik3 will fix this using the API GET request method. Tks.

M

On 5 November 2015 at 20:11, Miloš Mošić <notifications@github.com> wrote:

> That's the plan, we just haven't gotten to it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/770#issuecomment-154177050>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
According to the logs, we're not getting any undefined requests since the live view widget was fixed. Nice work @azharmalik3, closing this.
