### ISSUE TITLE
Recording widget UI issues on mobile

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#776]
- [ ] The recording schedule is hidden under the calendar (which seems to be the same problem with #641, but that ticket is closed. )
- [ ] Motion detection is floating on the calendar

Screenshot on Android:

![screenshot_2015-11-07-16-03-40](https://cloud.githubusercontent.com/assets/5046761/11035625/637526d4-86eb-11e5-855c-0244f561aa2c.png)

**Comment by liutingdu** [comment]
@muneeb2542 Is it deployed or is pending as pull request? I just tested it but seems doesn't work

**Comment by liutingdu** [comment]
@muneeb2542 @marcoherbst Any updates? It still doesn't work for me on mobile

**Comment by muneeb2542** [comment]
@liutingdu @marcoherbst  the page has been fixed and i have created a pull request for it.As soon as @azharmalik3 reviews it then i will then deploy it.

**Comment by liutingdu** [comment]
@muneeb2542  Thanks it works now :)
