### ISSUE TITLE
Signup email includes a message, but it's not nicely displayed.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#781]
![screenshot-mail google com 2015-11-11 15-31-27](https://cloud.githubusercontent.com/assets/5648894/11094766/83f84d74-8889-11e5-93a6-4500bc5b5685.png)

Better to give it its own grey box, like the URL gets, also be sure that we're passing line breaks nicely.

M

**Comment by muneeb2542** [comment]
it was an api issue and i have deployed the new layout.you can easily see new layout for signup message now.
