### ISSUE TITLE
Live view widget not working on iPhone6 , ios 9.1

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#789]
Tested on LDs phone with Chrome browser

http://www.carrolls.ie/livedublinwebcam

m

**Comment by marcoherbst** [comment]
@liutingdu  ... can you see if this is still a problem?

**Comment by liutingdu** [comment]
The problem was related to video view, now it's JPG everywhere (both iPhone & desktop), is it what we expected?

**Comment by marcoherbst** [comment]
@liutingdu  well noticed. No, that's not what is intended.

@mosic I'll send this to you as you're working on HLS recently. I see that the widget is reverted to jpegs while the dash still shows video.

Good morning :)

**Comment by marcoherbst** [comment]
@muneeb2542  .... likewise, can you take this?

**Comment by muneeb2542** [comment]
@marcoherbst  @Zulqarnain-Mustafa  is implementing websockets in ios right now.If the problem persists even after websocket implementation,then i will look into it.

 I'm leaving it for now.

**Comment by marcoherbst** [comment]
hmmm.... right, but are we talking about different things here ?

iOS app will have live view, correct.

Additionally, we've a live view widget, which I'm guessing Nain is not working on  ... but also needs to work cross-platform.

The dream was that this was re-useable code, I'm not sure the state of play on that. You can keep thinking about this and see that it's being done beautifully? LD is the sort of person who one could check in with if you're not sure.

**Comment by marcoherbst** [comment]
for the sake of closing a milestone, I'm moving this into 1.9.5

**Comment by liutingdu** [comment]
Just tried it again on my phone, it didn't autoplay when I open the page, but after clicking the 'play' button, the video shows up full screen, and it also works on screen rotation.

So now the only difference with Android browser is no autoplay, I guess that's not the initial issue?

**Comment by marcoherbst** [comment]
Correct. If you @muneeb2542 can fix the autoplay, then that would be nice. If not, close the issue anyway. (It may not be fixable).

**Comment by muneeb2542** [comment]
@marcoherbst  I don't there is a way to fix this autoplay issue from my side.

So closing this.

**Comment by marcoherbst** [comment]
:+1:
