### ISSUE TITLE
Fix Swagger Console Errors

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#790]
I think the swagger ones may not be fixable, but the webkit and google maps one should be.

Good luck, just work through the ones you can do. Make new issues if you like.

![console](https://cloud.githubusercontent.com/assets/5648894/11153895/d32f0f26-8a33-11e5-8f30-c4699b779df4.png)

**Comment by affan00** [comment]
Didn't find any console error related to 'webkitMovement' and 'geo map'. Found "no zalib library", "no iconv library"  warnings in console but they are related to swagger.

**Comment by marcoherbst** [comment]
Good stuff. Seems they might be fixed.

I get 2 other errors, I'll email you screenshots.

I believe the Swagger errors are not fixable, @mosic might explain. There
is a Swagger 2.0 out there, but not sure that it's worth it right now.


On 2 February 2016 at 09:18, Affan Qureshi <notifications@github.com> wrote:

> Didn't find any console error related to 'webkitMovement' and 'geo map'.
> Found "no zalib library", "no iconv library" warnings in console but they
> are related to swagger.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/790#issuecomment-178468041>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
I cleared google maps warnings recently: https://github.com/evercam/evercam-dashboard/commit/7494db7021110f2a2fad8f2c4c64ecf445c3010b.

Zlib and iconv library warnings are coming from a "shred" library which is used by Swagger. Modifying the source of it or upgrading to Swagger 2.0 isn't worth it at the moment. I think that currently not all components we use support Swagger 2.0.

**Comment by marcoherbst** [comment]
No more swagger = no more swagger errors :)
