### ISSUE TITLE
Live view tab / widget should have message on top of screen if evercam-media not giving image response

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#798]
This will be visible after few tries.

**Comment by marcoherbst** [comment]
@mosic  I'd like your opinion on this.

**Comment by mosic** [comment]
This sounds like a good idea. We could also have "Retrying..." message.

**Comment by marcoherbst** [comment]
Can you take this, Milos. I think the success of failure of it will be down to the detail and you're good at that.

**Comment by mosic** [comment]
@azharmalik3 This is a valid issue with the current state of the live view as it's not clear what's happening behind the scenes when there are no images shown, but this will be handled nicely when the online/offline detection gets better (planned soon), so I'll close this.
