### ISSUE TITLE
Use username as 'user_id' in Intercom

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#816]
@azharmalik3 just made the [change](https://github.com/evercam/evercam-dashboard/blob/17a7f02e90636f468ee891fb8af51170145b03d4/app/controllers/application_controller.rb#L42) of adding missing unique identifier ```user_id``` into Intercom: 

It's a numeric id stored in our database, which is not publicly available and is not used in the API at all. It doesn't make sense to use it as unique identifier in Intercom.

I've discussed this with Azhar and we both agree that the right field to use is 'username', so the task is to update 'user_id' with user's username for all existing users (including those who already has a number id)

**Comment by azharmalik3** [comment]
@liutingdu Done.

**Comment by liutingdu** [comment]
@azharmalik3 :+1:
