### ISSUE TITLE
Intercom: Identify user with 'user_id' instead of Email address

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#817]
This can only be done after https://github.com/evercam/evercam-dashboard/issues/816 (After we've collected user's username as unique identifier in Intercom)

Currently we are using Email address to identify user in [dashboard](https://github.com/evercam/evercam-dashboard/blob/17a7f02e90636f468ee891fb8af51170145b03d4/app/controllers/application_controller.rb#L35) and in Android. Email address is unique, but it's not recommended to use as unique id. Our system allows user changing it in Settings, which means if the user changes the Email address, all activities belongs to that user will no longer appears in Intercom.

It seems in our API, it also uses Email address as identifier for event tracking: [for example](https://github.com/evercam/evercam-api/blob/4b9c991261025f5110949a62e4e92083d4ee1fb1/app/api/v1/routes/camera_routes.rb#L196), it should be replaced with username too.

**Comment by azharmalik3** [comment]
@liutingdu  Done.

**Comment by liutingdu** [comment]
@azharmalik3  Thanks! It's done in Android too. 

But in API I see there are code that is identifying user with Email (I think) https://github.com/evercam/evercam-api/blob/4b9c991261025f5110949a62e4e92083d4ee1fb1/app/api/v1/routes/camera_routes.rb#L196

Do you think it should be replaced with username as well?

**Comment by azharmalik3** [comment]
@liutingdu sorry i forgot this to change.

**Comment by azharmalik3** [comment]
@liutingdu i fixed that.

**Comment by liutingdu** [comment]
:+1: I'll close this issue then
