### ISSUE TITLE
A nice message, overlaid over the image, when a camera is offline

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#822]
![screenshot 2015-12-02 13 59 41](https://cloud.githubusercontent.com/assets/5648894/11532669/3792982a-98fd-11e5-9797-8b65e8b76204.png)

**Comment by muneeb2542** [comment]
@marcoherbst  i wanted to ask what exactly do you want me write in the message?

**Comment by marcoherbst** [comment]
"Camera is Offline"

On 3 December 2015 at 10:17, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> i wanted to ask what
> exactly do you want me write in the message?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/822#issuecomment-161582065>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
ok tks

**Comment by muneeb2542** [comment]
@marcoherbst the message would be like this or do you want me to change something?
![screenshot from 2015-12-03 16 01 26](https://cloud.githubusercontent.com/assets/6482077/11558933/3795ec20-99d7-11e5-9a1e-7e316ffc6ba1.png)

**Comment by marcoherbst** [comment]
Perfect. Nice design :)


On 3 December 2015 at 11:02, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> the message would be like
> this or do you want me to change something?
> [image: screenshot from 2015-12-03 16 01 26]
> <https://cloud.githubusercontent.com/assets/6482077/11558933/3795ec20-99d7-11e5-9a1e-7e316ffc6ba1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/822#issuecomment-161599318>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
