### ISSUE TITLE
Use /cameras api to update cameras status on cameras page and left navigation.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#823]

**Comment by marcoherbst** [comment]
@mosic .... do you have any issues or comments on this? I know that you have some vision for how we ynchronise camera status, I just dont know what it is.

**Comment by mosic** [comment]
@marcoherbst Only thing I'd add that we have updating the sidebar already implemented: [sidebar.js.coffee](https://github.com/evercam/evercam-dashboard/blob/master/app/assets/javascripts/sidebar.js.coffee)

**Comment by marcoherbst** [comment]
I assume sidebar is the same things as left navigation. ... @azharmalik3 , if there's a lack of clarity here, I leave it to you to get to the bottom of it. I'll unassign @muneeb2542 and let @azharmalik3 reassign him when you're 100% confident that we're taking the right approach.

**Comment by azharmalik3** [comment]
@marcoherbst this is already implemented by Milos.
