### ISSUE TITLE
Add Intercom to dashboard

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#829]
This is their document: https://docs.intercom.io/install-on-your-web-product/use-javascript-to-install-intercom-on-any-web-site 

@marcoherbst

**Comment by marcoherbst** [comment]
Hi @muneeb2542 , We've enabled this in the past and then disabled it ... I think the time has come to get it working again. Before tackling this, you should check with Azhar and maybe have a voice call with me. The purpose is to make it easy for people to get help & support from us by starting a conversation.

**Comment by muneeb2542** [comment]
Done

**Comment by muneeb2542** [comment]
@marcoherbst  According to this ticket we had disabled this from dashboard.So according to above link by @liutingdu, I tried to make it work but the js code had authentication error,so then i used intercom rails configuration which was previously done on the site.Now what do you suggest should be done.

**Comment by muneeb2542** [comment]
@marcoherbst  intercom can now be accessed through the feedback.

**Comment by liutingdu** [comment]
:+1: 

Now it works the same way with Android
- No more pop up for new users
- The Intercom icon has been removed from main screen
- The Intercom dialog only shows up when I click 'Feedback'

Just one small question, in Android it's called 'Live Support' and in dashboard it's 'Feedback'. Which one should be renamed? @marcoherbst

**Comment by marcoherbst** [comment]
Excellent. Let's go for "Live Support".

Nice work LD & Muneeb.

On 19 January 2016 at 15:37, Liuting Du <notifications@github.com> wrote:

> [image: :+1:]
>
> Now it works the same way with Android
>
>    - No more pop up for new users
>    - The Intercom icon has been removed from main screen
>    - The Intercom dialog only shows up when I click 'Feedback'
>
> Just one small question, in Android it's called 'Live Support' and in
> dashboard it's 'Feedback'. Which one should be renamed? @marcoherbst
> <https://github.com/marcoherbst>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/829#issuecomment-172890726>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
