### ISSUE TITLE
Read only shared camera showing recording off

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#843]

**Comment by azharmalik3** [comment]
@marcoherbst i think we should remove recordings radio buttons from recordings tab because read only shared camera does not have rights to get cloud recordings from api.

Or

Change API get /cloud_recodings endpoint to return cloud settings, user has view rights or not.

**Comment by marcoherbst** [comment]
Option 1. Good.
M

On 21 December 2015 at 09:44, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> i think we should remove
> recordings radio buttons from recordings tab because read only shared
> camera does not have rights to get cloud recordings from api.
>
> Or
>
> Change API get /cloud_recodings endpoint to return cloud settings, user
> has view rights or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/843#issuecomment-166251842>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
done and deployed.
