### ISSUE TITLE
Add a toggle to enable/disable the camera offline notifications

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#846]
The setting should only be visible to camera owner as the notification email is sent to them. This will use the newly added field `is_online_email_owner_notification`: https://github.com/evercam/evercam-api/commit/e079bd691758b604f89df5fd030b398dac7920eb

**Comment by muneeb2542** [comment]
@mosic 
where do you want this toggle to be added,in the sharing panel?

**Comment by marcoherbst** [comment]
Put it at the bottom of this page, with a heading "Other". Label:
Notifications   . Text: Send email to owner when camera goes offline.

Also, this is not for owners only, make it available to change for anyone
that has full-rights.

For now, do the best job you can, we might change it later.

M

On 22 December 2015 at 05:48, Muneeb Rana <notifications@github.com> wrote:

> @mosic <https://github.com/mosic>
> where do you want this toggle to be added,in the sharing panel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/846#issuecomment-166516795>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
@marcoherbst  you mean details tab or sharing tab?

**Comment by marcoherbst** [comment]
Details

M

**Comment by muneeb2542** [comment]
Done

**Comment by muneeb2542** [comment]
This functionality has been added in the details page now and it is working fine.
