### ISSUE TITLE
At top of the dashboard ,the thumbnails are not displayed good and the list should extend to the bottom of the screen.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#856]

**Comment by muneeb2542** [comment]
@marcoherbst is this what you wanted?
![screenshot from 2016-01-07 19 12 41](https://cloud.githubusercontent.com/assets/6482077/12172444/c1ee0b08-b572-11e5-99b2-5feb5b4b50cf.png)

**Comment by marcoherbst** [comment]
50%

Pay attention to:

1. Border to left of image = border at top of image.
2. Dont use the red/green dots ... use the same style (strikethrough) as on
left nav.

M

On 7 January 2016 at 14:13, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> is this what you wanted?
> [image: screenshot from 2016-01-07 19 12 41]
> <https://cloud.githubusercontent.com/assets/6482077/12172444/c1ee0b08-b572-11e5-99b2-5feb5b4b50cf.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/856#issuecomment-169675414>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
@marcoherbst  You mean more like this
![screenshot from 2016-01-07 20 29 52](https://cloud.githubusercontent.com/assets/6482077/12174287/87eca2f6-b57d-11e5-9792-afe5f0d03d56.png)

**Comment by marcoherbst** [comment]
Bingo !

On 7 January 2016 at 15:30, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> You mean more like this
> [image: screenshot from 2016-01-07 20 29 52]
> <https://cloud.githubusercontent.com/assets/6482077/12174287/87eca2f6-b57d-11e5-9792-afe5f0d03d56.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/856#issuecomment-169695879>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
Done
