### ISSUE TITLE
Refresh status should be at the center of offline live view with the  'camera is offline' icon.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#866]

**Comment by marcoherbst** [comment]
Not instead of. In addition to. Beautifully done.

**Comment by marcoherbst** [comment]
.... I'm worried that this isn't super simple. Maybe send me a screenshot of what you're trying to do.

Also, remove the other offline text that appears at the bottom of the image currently. We will have nothing there.

M

**Comment by muneeb2542** [comment]
The Refresh Status will more or less be shown like this.The color can be easily changed plus i am going to add an animated loading image whenever it will be clicked on.
![screenshot from 2016-01-14 11-23-08](https://cloud.githubusercontent.com/assets/6482077/12317267/651e3990-bab1-11e5-8f63-c88b9b569a1c.png)

**Comment by muneeb2542** [comment]
@marcoherbst Do you want 'Refresh' icon be available for smaller screens? We right now just hide it at the bottom of the window.

**Comment by muneeb2542** [comment]
This functionality is added now.
