### ISSUE TITLE
Cloud Recordings for the widget are displayed weird and do not work.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#882]
![screenshot from 2016-01-21 14-14-09](https://cloud.githubusercontent.com/assets/6482077/12476257/e0c47076-c049-11e5-925b-c698db0e67f5.png)

**Comment by marcoherbst** [comment]
None of the radio buttons are selected when using this on the Android WebView

**Comment by muneeb2542** [comment]
Done
