### ISSUE TITLE
Last Login

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-dashboard#883]
1. go to your evercam- api-directory
 2.  `git pull origin master`
 3.  `bundle exec rake db:migrate`
 Now you will see a new field in User's table as ***last_login_at*** . 
Now add this for every user, when user will sign in its last login will be updated. 

NB :  `:last_login_at, :timestamptz, null: true`

**Comment by muneeb2542** [comment]
Done and deployed
