### ISSUE TITLE
Change the layout for the motion detection tab.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#901]

**Comment by affan00** [comment]
On motion detection setting "sensitivity" and "Reset time" should be disable on motion detection off and it should be enable when motion detection is on. and also the sensitivity bar is missing.  http://localhost:3000/v1/cameras/carrollszoocam. 
![motion-detection](https://cloud.githubusercontent.com/assets/14149453/12886145/2b94e31e-ce8d-11e5-9211-e15c50159e60.png)

**Comment by muneeb2542** [comment]
Done
