### ISSUE TITLE
while motion detection is on instead of shown thumbnails related to motion detection it shows just message "motion detection not enabled" 

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#904]
![error motion](https://cloud.githubusercontent.com/assets/14149453/12910028/9dff8b48-cf28-11e5-8195-fd69c2501cef.png)

![error-md](https://cloud.githubusercontent.com/assets/14149453/12909904/7fe14274-cf27-11e5-8fbf-2dad2cae0db1.png)

**Comment by muneeb2542** [comment]
@mosic @marcoherbst  
Milos is motion detection working in our application or not?
Plus i have checked the motion_level attribute in the snapshot table  for a camera whose motion detection is enabled for a long time,All the values are either null or 0.It used to work but now it is not.

Can you please look into this?

**Comment by muneeb2542** [comment]
It seems to be working now but more than 90% previous record has the value of 0 or either null.

**Comment by muneeb2542** [comment]
All the cameras which have cloud recordings enabled now have motion detection enabled also.
