### ISSUE TITLE
live view "video feed" play on chrome but not on firefox browser.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboard#905]

**Comment by muneeb2542** [comment]
This is not a llive feed issue.The live feed does not work on firefox because adobe flash is not installed.Just install the plugin for flash on firefox and the video will start running smoothly.

So i am closing this issue.

**Comment by affan00** [comment]
If this is the issue of the adobe flash player than we should show this
message to the client "to install adobe flash player for this video" so
that they can able to play the video.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani
