### ISSUE TITLE
Intercom - seems to have heaps of duplicate people

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#912]
@muneeb2542  ... this is one for you?

**Comment by muneeb2542** [comment]
@marcoherbst  i have corrected the code in dashboard for intercom.Now only one record will show for a user in the intercom account.

Now i will make a rake task to delete all the duplicate records from it.

**Comment by muneeb2542** [comment]
@marcoherbst i ran a rake task for deleting all the duplicate records created whenever a user sign up.
Almost 450 records were deleted.Now if we see a duplicate user in list it would mean that moth the records have diffrerent email and user id.

i am closing this task now.
