### ISSUE TITLE
Words in dashboard should not be wrapping.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#914]
When we enlarge a screen on dashboard there are clear signs of wordwrapping.
![unnamed](https://cloud.githubusercontent.com/assets/6482077/13049493/2bb51fd0-d40f-11e5-8c8d-a6c16ac1e862.png)

**Comment by affan00** [comment]
it's done.
![word-wraping](https://cloud.githubusercontent.com/assets/14149453/13105294/5ac3aa6e-d584-11e5-9bdc-5ff3ece6fe2d.png)
