### ISSUE TITLE
Improve the loading of video sequence.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#920]
Try loading a camera like this:
https://dash.evercam.io/v1/cameras/ballyguide-ptz

You'll see an old thumbnail, there is no loading animation, then there's a black screen, then the video arrives.

Let's use the thumbnail but it needs to be obvious that it's just a place holder, have a clear loading animation and no black screen - or, come up with a better suggestion yourself.

**Comment by affan00** [comment]
It's done already, Now we used default video-js loading spinner. So I am closing this.
