### ISSUE TITLE
We seem to loose map location quite often ... any ideas why? or how we could trace this?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#926]
Here's a camera, for example, that definitely had map info:
https://dash.evercam.io/v1/cameras/klausgardenf/details

Could you pay some attention to this and try and work out under what circumstances it gets reset.

**Comment by muneeb2542** [comment]
@marcoherbst  i have tried multiple scenarios on multiple cameras.Still not one time have i found that the map location reset.I even added a camera location to the above camera and expected a reset but still the location is there.

So for now i am closing this issue.I will ask Faisal to lookout for such things and inform me if ever they happen.

**Comment by marcoherbst** [comment]
Perfect. Tks.
