### ISSUE TITLE
Dashboard > Recordings > Schedule .... "Set Schedule" should be a pop-up window

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#935]
I think I had some reason for asking @mosic  not to do this originally, but really I see no other way to make this interface nice. Schedule will have be in a popup.

@affan00  can you give it a shot?

m

**Comment by marcoherbst** [comment]
![screenshot-adwords google com 2016-03-08 16-54-25](https://cloud.githubusercontent.com/assets/5648894/13608884/974282e2-e54e-11e5-9dcf-50afabf7ac20.png)

**Comment by affan00** [comment]
it's done
