### ISSUE TITLE
Main interface changes

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#949]
- [x] Bring the font sizes down a touch … (16 to 12 ?)
- [x] Change how offline cameras are shown. Try to copy how Android shows offline cameras … don’t use the strikethru, just do it like Android does with the icon.
- [x] Drop down menu: Reduce vertical spacing. Copy how Android has the dropdown list … less wasted vertical space, it seems nicer.  (see screenshot)
- [x] Remove Local Storage Functionality. It’s broken and we don’t know how to fix it. Do this in tabs (gone already) and in the Developer area.
- [x] Remove API Explorer from Camera View Tabs
If you need icons, get inspiration from Android.
- [x] Small link at bottom of Left Nav to “www.evercam.io” which opens in a new window. Always vertically aligned to the bottom.

**Comment by affan00** [comment]
it's done
