### ISSUE TITLE
The thumbnails on the main view should be periodically updated

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#953]
The `img` elements on the main page (https://dash.evercam.io/v1/cameras) should be updated every minute using the request to the same thumbnail url they have in `src` attribute. I added a class `camera-thumbnail` just now so they can be easily selected.

**Comment by marcoherbst** [comment]
Nice.
@muneeb2542 is this task complete from your PoV? Do you understand it and could implement it based on this info?

**Comment by muneeb2542** [comment]
@marcoherbst  i have setup a function, which will periodically update all the thumbnails on the index after every 60 seconds.

**Comment by mosic** [comment]
@muneeb2542 See my comments on the pull request: https://github.com/evercam/evercam-dashboard/pull/974/files

**Comment by muneeb2542** [comment]
@mosic i have made the appropriate changes to it in https://github.com/evercam/evercam-dashboard/pull/975.

**Comment by mosic** [comment]
@muneeb2542 Looks good, closing this.
