### ISSUE TITLE
Change billing messages

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#961]
- [x] Add the number of licenses required to the message e.g. when  “2” are needed to change the text to - You require 2 additional licences.
- [x] If a custom licence exists, we replace the “You require…” message with the “Please pay your custom licence…” message …. can you show this message in addition to the original one? instead of replacing it.

**Comment by azharmalik3** [comment]
Create the separate issue for last for the last #971.

**Comment by muneeb2542** [comment]
Done
