### ISSUE TITLE
Relocate "Copy From" on add a camera 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#967]
![screenshot-dash evercam io 2016-03-07 18-22-57](https://cloud.githubusercontent.com/assets/5648894/13578769/da98dc02-e491-11e5-8e3e-dc64e58081cb.png)

I think it would make more sense as shown.

While you're at it, I see no point in making the password field hidden since we show the camera password elsewhere.

**Comment by marcoherbst** [comment]
and, only show the "copy from" item if the user already has owned or full right cameras.

**Comment by affan00** [comment]
It's done.
