### ISSUE TITLE
snapshot navigator widget seems a little weird.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-dashboard#997]
This is probably because of the CSS files not being added in the widget CSS file.That is why the masking button is not displayed right.

**Comment by liutingdu** [comment]
@muneeb2542 Is it related to the issue on iPad? Or is it about the incorrection position of the calendar button on Android and iOS? (See screenshot attached)
![screen shot 2016-03-14 at 15 48 54](https://cloud.githubusercontent.com/assets/5046761/13750201/572bec68-e9fc-11e5-80c8-910301064c43.png)

**Comment by muneeb2542** [comment]
No, it is because of the incorrect position of the calendar button on
Android and iOS.

On 14 March 2016 at 20:49, Liuting Du <notifications@github.com> wrote:

> @muneeb2542 <https://github.com/muneeb2542> Is it related to the issue on
> iPad? Or is it about the incorrection position of the calendar button on
> Android and iOS? (See screenshot attached)
> [image: screen shot 2016-03-14 at 15 48 54]
> <https://cloud.githubusercontent.com/assets/5046761/13750201/572bec68-e9fc-11e5-80c8-910301064c43.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/997#issuecomment-196378068>
> .
>



-- 


Muneeb-ur-Rehman
Junior Software Developer
Evercam.io

**Comment by affan00** [comment]
it's fix now.
